package org.bukkit.event.player;

/** Auto-generated stub from paper-api-26.1.2.build.20-alpha.jar. See PLAN-FULL-STUBS.md. */
@SuppressWarnings({"unchecked", "rawtypes", "unused"})
public enum PlayerKickEvent$Cause {
    PLUGIN, WHITELIST, BANNED, IP_BANNED, KICK_COMMAND, FLYING_PLAYER, FLYING_VEHICLE, TIMEOUT, IDLING, INVALID_VEHICLE_MOVEMENT, INVALID_PLAYER_MOVEMENT, INVALID_ENTITY_ATTACKED, INVALID_PAYLOAD, INVALID_COOKIE, SPAM, ILLEGAL_ACTION, ILLEGAL_CHARACTERS, OUT_OF_ORDER_CHAT, UNSIGNED_CHAT, CHAT_VALIDATION_FAILED, EXPIRED_PROFILE_PUBLIC_KEY, INVALID_PUBLIC_KEY_SIGNATURE, TOO_MANY_PENDING_CHATS, SELF_INTERACTION, DUPLICATE_LOGIN, RESOURCE_PACK_REJECTION, RESTART_COMMAND, UNKNOWN;
}
