package org.joml;

/** Auto-generated stub from paper-api-26.1.2.build.20-alpha.jar. See PLAN-FULL-STUBS.md. */
@SuppressWarnings({"unchecked", "rawtypes", "unused"})
public interface Matrix3x2fc {
    float m00();
    float m01();
    float m10();
    float m11();
    float m20();
    float m21();
    org.joml.Matrix3x2f mul(org.joml.Matrix3x2fc arg0, org.joml.Matrix3x2f arg1);
    org.joml.Matrix3x2f mulLocal(org.joml.Matrix3x2fc arg0, org.joml.Matrix3x2f arg1);
    float determinant();
    org.joml.Matrix3x2f invert(org.joml.Matrix3x2f arg0);
    org.joml.Matrix3x2f translate(float arg0, float arg1, org.joml.Matrix3x2f arg2);
    org.joml.Matrix3x2f translate(org.joml.Vector2fc arg0, org.joml.Matrix3x2f arg1);
    org.joml.Matrix3x2f translateLocal(org.joml.Vector2fc arg0, org.joml.Matrix3x2f arg1);
    org.joml.Matrix3x2f translateLocal(float arg0, float arg1, org.joml.Matrix3x2f arg2);
    org.joml.Matrix3x2f get(org.joml.Matrix3x2f arg0);
    java.nio.FloatBuffer get(java.nio.FloatBuffer arg0);
    java.nio.FloatBuffer get(int arg0, java.nio.FloatBuffer arg1);
    java.nio.ByteBuffer get(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer get(int arg0, java.nio.ByteBuffer arg1);
    java.nio.FloatBuffer get3x3(java.nio.FloatBuffer arg0);
    java.nio.FloatBuffer get3x3(int arg0, java.nio.FloatBuffer arg1);
    java.nio.ByteBuffer get3x3(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer get3x3(int arg0, java.nio.ByteBuffer arg1);
    java.nio.FloatBuffer get4x4(java.nio.FloatBuffer arg0);
    java.nio.FloatBuffer get4x4(int arg0, java.nio.FloatBuffer arg1);
    java.nio.ByteBuffer get4x4(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer get4x4(int arg0, java.nio.ByteBuffer arg1);
    org.joml.Matrix3x2fc getToAddress(long arg0);
    org.joml.Matrix3x2fc getTransposedToAddress(long arg0);
    float[] get(float[] arg0, int arg1);
    float[] get(float[] arg0);
    float[] get3x3(float[] arg0, int arg1);
    float[] get3x3(float[] arg0);
    float[] get4x4(float[] arg0, int arg1);
    float[] get4x4(float[] arg0);
    org.joml.Matrix3x2f scale(float arg0, float arg1, org.joml.Matrix3x2f arg2);
    org.joml.Matrix3x2f scale(org.joml.Vector2fc arg0, org.joml.Matrix3x2f arg1);
    org.joml.Matrix3x2f scaleAroundLocal(float arg0, float arg1, float arg2, float arg3, org.joml.Matrix3x2f arg4);
    org.joml.Matrix3x2f scaleAroundLocal(float arg0, float arg1, float arg2, org.joml.Matrix3x2f arg3);
    org.joml.Matrix3x2f scale(float arg0, org.joml.Matrix3x2f arg1);
    org.joml.Matrix3x2f scaleLocal(float arg0, org.joml.Matrix3x2f arg1);
    org.joml.Matrix3x2f scaleLocal(float arg0, float arg1, org.joml.Matrix3x2f arg2);
    org.joml.Matrix3x2f scaleAround(float arg0, float arg1, float arg2, float arg3, org.joml.Matrix3x2f arg4);
    org.joml.Matrix3x2f scaleAround(float arg0, float arg1, float arg2, org.joml.Matrix3x2f arg3);
    org.joml.Vector3f transform(org.joml.Vector3f arg0);
    org.joml.Vector3f transform(org.joml.Vector3fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f transform(float arg0, float arg1, float arg2, org.joml.Vector3f arg3);
    org.joml.Vector2f transformPosition(org.joml.Vector2f arg0);
    org.joml.Vector2f transformPosition(org.joml.Vector2fc arg0, org.joml.Vector2f arg1);
    org.joml.Vector2f transformPosition(float arg0, float arg1, org.joml.Vector2f arg2);
    org.joml.Vector2f transformDirection(org.joml.Vector2f arg0);
    org.joml.Vector2f transformDirection(org.joml.Vector2fc arg0, org.joml.Vector2f arg1);
    org.joml.Vector2f transformDirection(float arg0, float arg1, org.joml.Vector2f arg2);
    org.joml.Matrix3x2f rotate(float arg0, org.joml.Matrix3x2f arg1);
    org.joml.Matrix3x2f rotateLocal(float arg0, org.joml.Matrix3x2f arg1);
    org.joml.Matrix3x2f rotateAbout(float arg0, float arg1, float arg2, org.joml.Matrix3x2f arg3);
    org.joml.Matrix3x2f rotateTo(org.joml.Vector2fc arg0, org.joml.Vector2fc arg1, org.joml.Matrix3x2f arg2);
    org.joml.Matrix3x2f view(float arg0, float arg1, float arg2, float arg3, org.joml.Matrix3x2f arg4);
    org.joml.Vector2f origin(org.joml.Vector2f arg0);
    float[] viewArea(float[] arg0);
    org.joml.Vector2f positiveX(org.joml.Vector2f arg0);
    org.joml.Vector2f normalizedPositiveX(org.joml.Vector2f arg0);
    org.joml.Vector2f positiveY(org.joml.Vector2f arg0);
    org.joml.Vector2f normalizedPositiveY(org.joml.Vector2f arg0);
    org.joml.Vector2f unproject(float arg0, float arg1, int[] arg2, org.joml.Vector2f arg3);
    org.joml.Vector2f unprojectInv(float arg0, float arg1, int[] arg2, org.joml.Vector2f arg3);
    boolean testPoint(float arg0, float arg1);
    boolean testCircle(float arg0, float arg1, float arg2);
    boolean testAar(float arg0, float arg1, float arg2, float arg3);
    boolean equals(org.joml.Matrix3x2fc arg0, float arg1);
    boolean isFinite();
}
