package org.joml;

/** Auto-generated stub from paper-api-26.1.2.build.20-alpha.jar. See PLAN-FULL-STUBS.md. */
@SuppressWarnings({"unchecked", "rawtypes", "unused"})
public interface Matrix3x2dc {
    double m00();
    double m01();
    double m10();
    double m11();
    double m20();
    double m21();
    org.joml.Matrix3x2d mul(org.joml.Matrix3x2dc arg0, org.joml.Matrix3x2d arg1);
    org.joml.Matrix3x2d mulLocal(org.joml.Matrix3x2dc arg0, org.joml.Matrix3x2d arg1);
    double determinant();
    org.joml.Matrix3x2d invert(org.joml.Matrix3x2d arg0);
    org.joml.Matrix3x2d translate(double arg0, double arg1, org.joml.Matrix3x2d arg2);
    org.joml.Matrix3x2d translate(org.joml.Vector2dc arg0, org.joml.Matrix3x2d arg1);
    org.joml.Matrix3x2d translateLocal(org.joml.Vector2dc arg0, org.joml.Matrix3x2d arg1);
    org.joml.Matrix3x2d translateLocal(double arg0, double arg1, org.joml.Matrix3x2d arg2);
    org.joml.Matrix3x2d get(org.joml.Matrix3x2d arg0);
    java.nio.DoubleBuffer get(java.nio.DoubleBuffer arg0);
    java.nio.DoubleBuffer get(int arg0, java.nio.DoubleBuffer arg1);
    java.nio.ByteBuffer get(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer get(int arg0, java.nio.ByteBuffer arg1);
    java.nio.DoubleBuffer getTransposed(java.nio.DoubleBuffer arg0);
    java.nio.DoubleBuffer getTransposed(int arg0, java.nio.DoubleBuffer arg1);
    java.nio.ByteBuffer getTransposed(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer getTransposed(int arg0, java.nio.ByteBuffer arg1);
    java.nio.FloatBuffer getTransposed(java.nio.FloatBuffer arg0);
    java.nio.FloatBuffer getTransposed(int arg0, java.nio.FloatBuffer arg1);
    java.nio.ByteBuffer getTransposedFloats(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer getTransposedFloats(int arg0, java.nio.ByteBuffer arg1);
    java.nio.DoubleBuffer get3x3(java.nio.DoubleBuffer arg0);
    java.nio.DoubleBuffer get3x3(int arg0, java.nio.DoubleBuffer arg1);
    java.nio.ByteBuffer get3x3(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer get3x3(int arg0, java.nio.ByteBuffer arg1);
    java.nio.DoubleBuffer get4x4(java.nio.DoubleBuffer arg0);
    java.nio.DoubleBuffer get4x4(int arg0, java.nio.DoubleBuffer arg1);
    java.nio.ByteBuffer get4x4(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer get4x4(int arg0, java.nio.ByteBuffer arg1);
    org.joml.Matrix3x2dc getToAddress(long arg0);
    org.joml.Matrix3x2dc getTransposedToAddress(long arg0);
    double[] get(double[] arg0, int arg1);
    double[] get(double[] arg0);
    double[] get3x3(double[] arg0, int arg1);
    double[] get3x3(double[] arg0);
    double[] get4x4(double[] arg0, int arg1);
    double[] get4x4(double[] arg0);
    org.joml.Matrix3x2d scale(double arg0, double arg1, org.joml.Matrix3x2d arg2);
    org.joml.Matrix3x2d scale(org.joml.Vector2dc arg0, org.joml.Matrix3x2d arg1);
    org.joml.Matrix3x2d scale(org.joml.Vector2fc arg0, org.joml.Matrix3x2d arg1);
    org.joml.Matrix3x2d scaleLocal(double arg0, org.joml.Matrix3x2d arg1);
    org.joml.Matrix3x2d scaleLocal(double arg0, double arg1, org.joml.Matrix3x2d arg2);
    org.joml.Matrix3x2d scaleAroundLocal(double arg0, double arg1, double arg2, double arg3, org.joml.Matrix3x2d arg4);
    org.joml.Matrix3x2d scaleAroundLocal(double arg0, double arg1, double arg2, org.joml.Matrix3x2d arg3);
    org.joml.Matrix3x2d scale(double arg0, org.joml.Matrix3x2d arg1);
    org.joml.Matrix3x2d scaleAround(double arg0, double arg1, double arg2, double arg3, org.joml.Matrix3x2d arg4);
    org.joml.Matrix3x2d scaleAround(double arg0, double arg1, double arg2, org.joml.Matrix3x2d arg3);
    org.joml.Vector3d transform(org.joml.Vector3d arg0);
    org.joml.Vector3d transform(org.joml.Vector3dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d transform(double arg0, double arg1, double arg2, org.joml.Vector3d arg3);
    org.joml.Vector2d transformPosition(org.joml.Vector2d arg0);
    org.joml.Vector2d transformPosition(org.joml.Vector2dc arg0, org.joml.Vector2d arg1);
    org.joml.Vector2d transformPosition(double arg0, double arg1, org.joml.Vector2d arg2);
    org.joml.Vector2d transformDirection(org.joml.Vector2d arg0);
    org.joml.Vector2d transformDirection(org.joml.Vector2dc arg0, org.joml.Vector2d arg1);
    org.joml.Vector2d transformDirection(double arg0, double arg1, org.joml.Vector2d arg2);
    org.joml.Matrix3x2d rotate(double arg0, org.joml.Matrix3x2d arg1);
    org.joml.Matrix3x2d rotateLocal(double arg0, org.joml.Matrix3x2d arg1);
    org.joml.Matrix3x2d rotateAbout(double arg0, double arg1, double arg2, org.joml.Matrix3x2d arg3);
    org.joml.Matrix3x2d rotateTo(org.joml.Vector2dc arg0, org.joml.Vector2dc arg1, org.joml.Matrix3x2d arg2);
    org.joml.Matrix3x2d view(double arg0, double arg1, double arg2, double arg3, org.joml.Matrix3x2d arg4);
    org.joml.Vector2d origin(org.joml.Vector2d arg0);
    double[] viewArea(double[] arg0);
    org.joml.Vector2d positiveX(org.joml.Vector2d arg0);
    org.joml.Vector2d normalizedPositiveX(org.joml.Vector2d arg0);
    org.joml.Vector2d positiveY(org.joml.Vector2d arg0);
    org.joml.Vector2d normalizedPositiveY(org.joml.Vector2d arg0);
    org.joml.Vector2d unproject(double arg0, double arg1, int[] arg2, org.joml.Vector2d arg3);
    org.joml.Vector2d unprojectInv(double arg0, double arg1, int[] arg2, org.joml.Vector2d arg3);
    boolean testPoint(double arg0, double arg1);
    boolean testCircle(double arg0, double arg1, double arg2);
    boolean testAar(double arg0, double arg1, double arg2, double arg3);
    boolean equals(org.joml.Matrix3x2dc arg0, double arg1);
    boolean isFinite();
}
