package org.joml;

/** Auto-generated stub from paper-api-26.1.2.build.20-alpha.jar. See PLAN-FULL-STUBS.md. */
@SuppressWarnings({"unchecked", "rawtypes", "unused"})
public interface Matrix4dc {
    public static final int PLANE_NX = 0;
    public static final int PLANE_PX = 1;
    public static final int PLANE_NY = 2;
    public static final int PLANE_PY = 3;
    public static final int PLANE_NZ = 4;
    public static final int PLANE_PZ = 5;
    public static final int CORNER_NXNYNZ = 0;
    public static final int CORNER_PXNYNZ = 1;
    public static final int CORNER_PXPYNZ = 2;
    public static final int CORNER_NXPYNZ = 3;
    public static final int CORNER_PXNYPZ = 4;
    public static final int CORNER_NXNYPZ = 5;
    public static final int CORNER_NXPYPZ = 6;
    public static final int CORNER_PXPYPZ = 7;
    public static final byte PROPERTY_UNKNOWN = (byte) 0;
    public static final byte PROPERTY_PERSPECTIVE = (byte) 1;
    public static final byte PROPERTY_AFFINE = (byte) 2;
    public static final byte PROPERTY_IDENTITY = (byte) 4;
    public static final byte PROPERTY_TRANSLATION = (byte) 8;
    public static final byte PROPERTY_ORTHONORMAL = (byte) 16;
    int properties();
    double m00();
    double m01();
    double m02();
    double m03();
    double m10();
    double m11();
    double m12();
    double m13();
    double m20();
    double m21();
    double m22();
    double m23();
    double m30();
    double m31();
    double m32();
    double m33();
    org.joml.Matrix4d mul(org.joml.Matrix4dc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d mul0(org.joml.Matrix4dc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d mul(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, double arg6, double arg7, double arg8, double arg9, double arg10, double arg11, double arg12, double arg13, double arg14, double arg15, org.joml.Matrix4d arg16);
    org.joml.Matrix4d mul3x3(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, double arg6, double arg7, double arg8, org.joml.Matrix4d arg9);
    org.joml.Matrix4d mulLocal(org.joml.Matrix4dc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d mulLocalAffine(org.joml.Matrix4dc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d mul(org.joml.Matrix3x2dc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d mul(org.joml.Matrix3x2fc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d mul(org.joml.Matrix4x3dc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d mul(org.joml.Matrix4x3fc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d mul(org.joml.Matrix4fc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d mulPerspectiveAffine(org.joml.Matrix4dc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d mulPerspectiveAffine(org.joml.Matrix4x3dc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d mulAffineR(org.joml.Matrix4dc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d mulAffine(org.joml.Matrix4dc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d mulTranslationAffine(org.joml.Matrix4dc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d mulOrthoAffine(org.joml.Matrix4dc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d fma4x3(org.joml.Matrix4dc arg0, double arg1, org.joml.Matrix4d arg2);
    org.joml.Matrix4d add(org.joml.Matrix4dc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d sub(org.joml.Matrix4dc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d mulComponentWise(org.joml.Matrix4dc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d add4x3(org.joml.Matrix4dc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d add4x3(org.joml.Matrix4fc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d sub4x3(org.joml.Matrix4dc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d mul4x3ComponentWise(org.joml.Matrix4dc arg0, org.joml.Matrix4d arg1);
    double determinant();
    double determinant3x3();
    double determinantAffine();
    org.joml.Matrix4d invert(org.joml.Matrix4d arg0);
    org.joml.Matrix4d invertPerspective(org.joml.Matrix4d arg0);
    org.joml.Matrix4d invertFrustum(org.joml.Matrix4d arg0);
    org.joml.Matrix4d invertOrtho(org.joml.Matrix4d arg0);
    org.joml.Matrix4d invertPerspectiveView(org.joml.Matrix4dc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d invertPerspectiveView(org.joml.Matrix4x3dc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d invertAffine(org.joml.Matrix4d arg0);
    org.joml.Matrix4d transpose(org.joml.Matrix4d arg0);
    org.joml.Matrix4d transpose3x3(org.joml.Matrix4d arg0);
    org.joml.Matrix3d transpose3x3(org.joml.Matrix3d arg0);
    org.joml.Vector3d getTranslation(org.joml.Vector3d arg0);
    org.joml.Vector3d getScale(org.joml.Vector3d arg0);
    org.joml.Matrix4d get(org.joml.Matrix4d arg0);
    org.joml.Matrix4x3d get4x3(org.joml.Matrix4x3d arg0);
    org.joml.Matrix3d get3x3(org.joml.Matrix3d arg0);
    org.joml.Quaternionf getUnnormalizedRotation(org.joml.Quaternionf arg0);
    org.joml.Quaternionf getNormalizedRotation(org.joml.Quaternionf arg0);
    org.joml.Quaterniond getUnnormalizedRotation(org.joml.Quaterniond arg0);
    org.joml.Quaterniond getNormalizedRotation(org.joml.Quaterniond arg0);
    java.nio.DoubleBuffer get(java.nio.DoubleBuffer arg0);
    java.nio.DoubleBuffer get(int arg0, java.nio.DoubleBuffer arg1);
    java.nio.FloatBuffer get(java.nio.FloatBuffer arg0);
    java.nio.FloatBuffer get(int arg0, java.nio.FloatBuffer arg1);
    java.nio.ByteBuffer get(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer get(int arg0, java.nio.ByteBuffer arg1);
    org.joml.Matrix4dc getToAddress(long arg0);
    org.joml.Matrix4dc getTransposedToAddress(long arg0);
    java.nio.ByteBuffer getFloats(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer getFloats(int arg0, java.nio.ByteBuffer arg1);
    double[] get(double[] arg0, int arg1);
    double[] get(double[] arg0);
    float[] get(float[] arg0, int arg1);
    float[] get(float[] arg0);
    java.nio.DoubleBuffer getTransposed(java.nio.DoubleBuffer arg0);
    java.nio.DoubleBuffer getTransposed(int arg0, java.nio.DoubleBuffer arg1);
    java.nio.ByteBuffer getTransposed(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer getTransposed(int arg0, java.nio.ByteBuffer arg1);
    java.nio.FloatBuffer getTransposed(java.nio.FloatBuffer arg0);
    java.nio.FloatBuffer getTransposed(int arg0, java.nio.FloatBuffer arg1);
    java.nio.ByteBuffer getTransposedFloats(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer getTransposedFloats(int arg0, java.nio.ByteBuffer arg1);
    java.nio.DoubleBuffer get4x3Transposed(java.nio.DoubleBuffer arg0);
    java.nio.DoubleBuffer get4x3Transposed(int arg0, java.nio.DoubleBuffer arg1);
    java.nio.ByteBuffer get4x3Transposed(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer get4x3Transposed(int arg0, java.nio.ByteBuffer arg1);
    org.joml.Vector4d transform(org.joml.Vector4d arg0);
    org.joml.Vector4d transform(org.joml.Vector4dc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d transform(double arg0, double arg1, double arg2, double arg3, org.joml.Vector4d arg4);
    org.joml.Vector4d transformTranspose(org.joml.Vector4d arg0);
    org.joml.Vector4d transformTranspose(org.joml.Vector4dc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d transformTranspose(double arg0, double arg1, double arg2, double arg3, org.joml.Vector4d arg4);
    org.joml.Vector4d transformProject(org.joml.Vector4d arg0);
    org.joml.Vector4d transformProject(org.joml.Vector4dc arg0, org.joml.Vector4d arg1);
    org.joml.Vector3d transformProject(org.joml.Vector4dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector4d transformProject(double arg0, double arg1, double arg2, double arg3, org.joml.Vector4d arg4);
    org.joml.Vector3d transformProject(org.joml.Vector3d arg0);
    org.joml.Vector3d transformProject(org.joml.Vector3dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d transformProject(double arg0, double arg1, double arg2, org.joml.Vector3d arg3);
    org.joml.Vector3d transformProject(double arg0, double arg1, double arg2, double arg3, org.joml.Vector3d arg4);
    org.joml.Vector3d transformPosition(org.joml.Vector3d arg0);
    org.joml.Vector3d transformPosition(org.joml.Vector3dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d transformPosition(double arg0, double arg1, double arg2, org.joml.Vector3d arg3);
    org.joml.Vector3d transformDirection(org.joml.Vector3d arg0);
    org.joml.Vector3d transformDirection(org.joml.Vector3dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3f transformDirection(org.joml.Vector3f arg0);
    org.joml.Vector3f transformDirection(org.joml.Vector3fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3d transformDirection(double arg0, double arg1, double arg2, org.joml.Vector3d arg3);
    org.joml.Vector3f transformDirection(double arg0, double arg1, double arg2, org.joml.Vector3f arg3);
    org.joml.Vector4d transformAffine(org.joml.Vector4d arg0);
    org.joml.Vector4d transformAffine(org.joml.Vector4dc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d transformAffine(double arg0, double arg1, double arg2, double arg3, org.joml.Vector4d arg4);
    org.joml.Matrix4d scale(org.joml.Vector3dc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d scale(double arg0, double arg1, double arg2, org.joml.Matrix4d arg3);
    org.joml.Matrix4d scale(double arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d scaleXY(double arg0, double arg1, org.joml.Matrix4d arg2);
    org.joml.Matrix4d scaleAround(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, org.joml.Matrix4d arg6);
    org.joml.Matrix4d scaleAround(double arg0, double arg1, double arg2, double arg3, org.joml.Matrix4d arg4);
    org.joml.Matrix4d scaleLocal(double arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d scaleLocal(double arg0, double arg1, double arg2, org.joml.Matrix4d arg3);
    org.joml.Matrix4d scaleAroundLocal(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, org.joml.Matrix4d arg6);
    org.joml.Matrix4d scaleAroundLocal(double arg0, double arg1, double arg2, double arg3, org.joml.Matrix4d arg4);
    org.joml.Matrix4d rotate(double arg0, double arg1, double arg2, double arg3, org.joml.Matrix4d arg4);
    org.joml.Matrix4d rotateTranslation(double arg0, double arg1, double arg2, double arg3, org.joml.Matrix4d arg4);
    org.joml.Matrix4d rotateAffine(double arg0, double arg1, double arg2, double arg3, org.joml.Matrix4d arg4);
    org.joml.Matrix4d rotateAroundAffine(org.joml.Quaterniondc arg0, double arg1, double arg2, double arg3, org.joml.Matrix4d arg4);
    org.joml.Matrix4d rotateAround(org.joml.Quaterniondc arg0, double arg1, double arg2, double arg3, org.joml.Matrix4d arg4);
    org.joml.Matrix4d rotateLocal(double arg0, double arg1, double arg2, double arg3, org.joml.Matrix4d arg4);
    org.joml.Matrix4d rotateLocalX(double arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d rotateLocalY(double arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d rotateLocalZ(double arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d rotateAroundLocal(org.joml.Quaterniondc arg0, double arg1, double arg2, double arg3, org.joml.Matrix4d arg4);
    org.joml.Matrix4d translate(org.joml.Vector3dc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d translate(org.joml.Vector3fc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d translate(double arg0, double arg1, double arg2, org.joml.Matrix4d arg3);
    org.joml.Matrix4d translateLocal(org.joml.Vector3fc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d translateLocal(org.joml.Vector3dc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d translateLocal(double arg0, double arg1, double arg2, org.joml.Matrix4d arg3);
    org.joml.Matrix4d rotateX(double arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d rotateY(double arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d rotateZ(double arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d rotateTowardsXY(double arg0, double arg1, org.joml.Matrix4d arg2);
    org.joml.Matrix4d rotateXYZ(double arg0, double arg1, double arg2, org.joml.Matrix4d arg3);
    org.joml.Matrix4d rotateAffineXYZ(double arg0, double arg1, double arg2, org.joml.Matrix4d arg3);
    org.joml.Matrix4d rotateZYX(double arg0, double arg1, double arg2, org.joml.Matrix4d arg3);
    org.joml.Matrix4d rotateAffineZYX(double arg0, double arg1, double arg2, org.joml.Matrix4d arg3);
    org.joml.Matrix4d rotateYXZ(double arg0, double arg1, double arg2, org.joml.Matrix4d arg3);
    org.joml.Matrix4d rotateAffineYXZ(double arg0, double arg1, double arg2, org.joml.Matrix4d arg3);
    org.joml.Matrix4d rotate(org.joml.Quaterniondc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d rotate(org.joml.Quaternionfc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d rotateAffine(org.joml.Quaterniondc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d rotateTranslation(org.joml.Quaterniondc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d rotateTranslation(org.joml.Quaternionfc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d rotateLocal(org.joml.Quaterniondc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d rotateAffine(org.joml.Quaternionfc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d rotateLocal(org.joml.Quaternionfc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d rotate(org.joml.AxisAngle4f arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d rotate(org.joml.AxisAngle4d arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d rotate(double arg0, org.joml.Vector3dc arg1, org.joml.Matrix4d arg2);
    org.joml.Matrix4d rotate(double arg0, org.joml.Vector3fc arg1, org.joml.Matrix4d arg2);
    org.joml.Vector4d getRow(int arg0, org.joml.Vector4d arg1) throws java.lang.IndexOutOfBoundsException;
    org.joml.Vector3d getRow(int arg0, org.joml.Vector3d arg1) throws java.lang.IndexOutOfBoundsException;
    org.joml.Vector4d getColumn(int arg0, org.joml.Vector4d arg1) throws java.lang.IndexOutOfBoundsException;
    org.joml.Vector3d getColumn(int arg0, org.joml.Vector3d arg1) throws java.lang.IndexOutOfBoundsException;
    double get(int arg0, int arg1);
    double getRowColumn(int arg0, int arg1);
    org.joml.Matrix4d normal(org.joml.Matrix4d arg0);
    org.joml.Matrix3d normal(org.joml.Matrix3d arg0);
    org.joml.Matrix3d cofactor3x3(org.joml.Matrix3d arg0);
    org.joml.Matrix4d cofactor3x3(org.joml.Matrix4d arg0);
    org.joml.Matrix4d normalize3x3(org.joml.Matrix4d arg0);
    org.joml.Matrix3d normalize3x3(org.joml.Matrix3d arg0);
    org.joml.Vector4d unproject(double arg0, double arg1, double arg2, int[] arg3, org.joml.Vector4d arg4);
    org.joml.Vector3d unproject(double arg0, double arg1, double arg2, int[] arg3, org.joml.Vector3d arg4);
    org.joml.Vector4d unproject(org.joml.Vector3dc arg0, int[] arg1, org.joml.Vector4d arg2);
    org.joml.Vector3d unproject(org.joml.Vector3dc arg0, int[] arg1, org.joml.Vector3d arg2);
    org.joml.Matrix4d unprojectRay(double arg0, double arg1, int[] arg2, org.joml.Vector3d arg3, org.joml.Vector3d arg4);
    org.joml.Matrix4d unprojectRay(org.joml.Vector2dc arg0, int[] arg1, org.joml.Vector3d arg2, org.joml.Vector3d arg3);
    org.joml.Vector4d unprojectInv(org.joml.Vector3dc arg0, int[] arg1, org.joml.Vector4d arg2);
    org.joml.Vector4d unprojectInv(double arg0, double arg1, double arg2, int[] arg3, org.joml.Vector4d arg4);
    org.joml.Vector3d unprojectInv(org.joml.Vector3dc arg0, int[] arg1, org.joml.Vector3d arg2);
    org.joml.Vector3d unprojectInv(double arg0, double arg1, double arg2, int[] arg3, org.joml.Vector3d arg4);
    org.joml.Matrix4d unprojectInvRay(org.joml.Vector2dc arg0, int[] arg1, org.joml.Vector3d arg2, org.joml.Vector3d arg3);
    org.joml.Matrix4d unprojectInvRay(double arg0, double arg1, int[] arg2, org.joml.Vector3d arg3, org.joml.Vector3d arg4);
    org.joml.Vector4d project(double arg0, double arg1, double arg2, int[] arg3, org.joml.Vector4d arg4);
    org.joml.Vector3d project(double arg0, double arg1, double arg2, int[] arg3, org.joml.Vector3d arg4);
    org.joml.Vector4d project(org.joml.Vector3dc arg0, int[] arg1, org.joml.Vector4d arg2);
    org.joml.Vector3d project(org.joml.Vector3dc arg0, int[] arg1, org.joml.Vector3d arg2);
    org.joml.Matrix4d reflect(double arg0, double arg1, double arg2, double arg3, org.joml.Matrix4d arg4);
    org.joml.Matrix4d reflect(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, org.joml.Matrix4d arg6);
    org.joml.Matrix4d reflect(org.joml.Quaterniondc arg0, org.joml.Vector3dc arg1, org.joml.Matrix4d arg2);
    org.joml.Matrix4d reflect(org.joml.Vector3dc arg0, org.joml.Vector3dc arg1, org.joml.Matrix4d arg2);
    org.joml.Matrix4d ortho(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, boolean arg6, org.joml.Matrix4d arg7);
    org.joml.Matrix4d ortho(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, org.joml.Matrix4d arg6);
    org.joml.Matrix4d orthoLH(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, boolean arg6, org.joml.Matrix4d arg7);
    org.joml.Matrix4d orthoLH(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, org.joml.Matrix4d arg6);
    org.joml.Matrix4d orthoSymmetric(double arg0, double arg1, double arg2, double arg3, boolean arg4, org.joml.Matrix4d arg5);
    org.joml.Matrix4d orthoSymmetric(double arg0, double arg1, double arg2, double arg3, org.joml.Matrix4d arg4);
    org.joml.Matrix4d orthoSymmetricLH(double arg0, double arg1, double arg2, double arg3, boolean arg4, org.joml.Matrix4d arg5);
    org.joml.Matrix4d orthoSymmetricLH(double arg0, double arg1, double arg2, double arg3, org.joml.Matrix4d arg4);
    org.joml.Matrix4d ortho2D(double arg0, double arg1, double arg2, double arg3, org.joml.Matrix4d arg4);
    org.joml.Matrix4d ortho2DLH(double arg0, double arg1, double arg2, double arg3, org.joml.Matrix4d arg4);
    org.joml.Matrix4d lookAlong(org.joml.Vector3dc arg0, org.joml.Vector3dc arg1, org.joml.Matrix4d arg2);
    org.joml.Matrix4d lookAlong(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, org.joml.Matrix4d arg6);
    org.joml.Matrix4d lookAt(org.joml.Vector3dc arg0, org.joml.Vector3dc arg1, org.joml.Vector3dc arg2, org.joml.Matrix4d arg3);
    org.joml.Matrix4d lookAt(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, double arg6, double arg7, double arg8, org.joml.Matrix4d arg9);
    org.joml.Matrix4d lookAtPerspective(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, double arg6, double arg7, double arg8, org.joml.Matrix4d arg9);
    org.joml.Matrix4d lookAtLH(org.joml.Vector3dc arg0, org.joml.Vector3dc arg1, org.joml.Vector3dc arg2, org.joml.Matrix4d arg3);
    org.joml.Matrix4d lookAtLH(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, double arg6, double arg7, double arg8, org.joml.Matrix4d arg9);
    org.joml.Matrix4d lookAtPerspectiveLH(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, double arg6, double arg7, double arg8, org.joml.Matrix4d arg9);
    org.joml.Matrix4d tile(int arg0, int arg1, int arg2, int arg3, org.joml.Matrix4d arg4);
    org.joml.Matrix4d perspective(double arg0, double arg1, double arg2, double arg3, boolean arg4, org.joml.Matrix4d arg5);
    org.joml.Matrix4d perspective(double arg0, double arg1, double arg2, double arg3, org.joml.Matrix4d arg4);
    org.joml.Matrix4d perspectiveRect(double arg0, double arg1, double arg2, double arg3, boolean arg4, org.joml.Matrix4d arg5);
    org.joml.Matrix4d perspectiveRect(double arg0, double arg1, double arg2, double arg3, org.joml.Matrix4d arg4);
    org.joml.Matrix4d perspectiveOffCenter(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, boolean arg6, org.joml.Matrix4d arg7);
    org.joml.Matrix4d perspectiveOffCenter(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, org.joml.Matrix4d arg6);
    org.joml.Matrix4d perspectiveOffCenterFov(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, boolean arg6, org.joml.Matrix4d arg7);
    org.joml.Matrix4d perspectiveOffCenterFov(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, org.joml.Matrix4d arg6);
    org.joml.Matrix4d perspectiveOffCenterFovLH(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, boolean arg6, org.joml.Matrix4d arg7);
    org.joml.Matrix4d perspectiveOffCenterFovLH(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, org.joml.Matrix4d arg6);
    org.joml.Matrix4d perspectiveLH(double arg0, double arg1, double arg2, double arg3, boolean arg4, org.joml.Matrix4d arg5);
    org.joml.Matrix4d perspectiveLH(double arg0, double arg1, double arg2, double arg3, org.joml.Matrix4d arg4);
    org.joml.Matrix4d frustum(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, boolean arg6, org.joml.Matrix4d arg7);
    org.joml.Matrix4d frustum(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, org.joml.Matrix4d arg6);
    org.joml.Matrix4d frustumLH(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, boolean arg6, org.joml.Matrix4d arg7);
    org.joml.Matrix4d frustumLH(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, org.joml.Matrix4d arg6);
    org.joml.Vector4d frustumPlane(int arg0, org.joml.Vector4d arg1);
    org.joml.Vector3d frustumCorner(int arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d perspectiveOrigin(org.joml.Vector3d arg0);
    org.joml.Vector3d perspectiveInvOrigin(org.joml.Vector3d arg0);
    double perspectiveFov();
    double perspectiveNear();
    double perspectiveFar();
    org.joml.Vector3d frustumRayDir(double arg0, double arg1, org.joml.Vector3d arg2);
    org.joml.Vector3d positiveZ(org.joml.Vector3d arg0);
    org.joml.Vector3d normalizedPositiveZ(org.joml.Vector3d arg0);
    org.joml.Vector3d positiveX(org.joml.Vector3d arg0);
    org.joml.Vector3d normalizedPositiveX(org.joml.Vector3d arg0);
    org.joml.Vector3d positiveY(org.joml.Vector3d arg0);
    org.joml.Vector3d normalizedPositiveY(org.joml.Vector3d arg0);
    org.joml.Vector3d originAffine(org.joml.Vector3d arg0);
    org.joml.Vector3d origin(org.joml.Vector3d arg0);
    org.joml.Matrix4d shadow(org.joml.Vector4dc arg0, double arg1, double arg2, double arg3, double arg4, org.joml.Matrix4d arg5);
    org.joml.Matrix4d shadow(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, double arg6, double arg7, org.joml.Matrix4d arg8);
    org.joml.Matrix4d shadow(org.joml.Vector4dc arg0, org.joml.Matrix4dc arg1, org.joml.Matrix4d arg2);
    org.joml.Matrix4d shadow(double arg0, double arg1, double arg2, double arg3, org.joml.Matrix4dc arg4, org.joml.Matrix4d arg5);
    org.joml.Matrix4d pick(double arg0, double arg1, double arg2, double arg3, int[] arg4, org.joml.Matrix4d arg5);
    boolean isAffine();
    org.joml.Matrix4d arcball(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, org.joml.Matrix4d arg6);
    org.joml.Matrix4d arcball(double arg0, org.joml.Vector3dc arg1, double arg2, double arg3, org.joml.Matrix4d arg4);
    org.joml.Matrix4d projectedGridRange(org.joml.Matrix4dc arg0, double arg1, double arg2, org.joml.Matrix4d arg3);
    org.joml.Matrix4d perspectiveFrustumSlice(double arg0, double arg1, org.joml.Matrix4d arg2);
    org.joml.Matrix4d orthoCrop(org.joml.Matrix4dc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d transformAab(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, org.joml.Vector3d arg6, org.joml.Vector3d arg7);
    org.joml.Matrix4d transformAab(org.joml.Vector3dc arg0, org.joml.Vector3dc arg1, org.joml.Vector3d arg2, org.joml.Vector3d arg3);
    org.joml.Matrix4d lerp(org.joml.Matrix4dc arg0, double arg1, org.joml.Matrix4d arg2);
    org.joml.Matrix4d rotateTowards(org.joml.Vector3dc arg0, org.joml.Vector3dc arg1, org.joml.Matrix4d arg2);
    org.joml.Matrix4d rotateTowards(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, org.joml.Matrix4d arg6);
    org.joml.Vector3d getEulerAnglesXYZ(org.joml.Vector3d arg0);
    org.joml.Vector3d getEulerAnglesZYX(org.joml.Vector3d arg0);
    org.joml.Vector3d getEulerAnglesYXZ(org.joml.Vector3d arg0);
    boolean testPoint(double arg0, double arg1, double arg2);
    boolean testSphere(double arg0, double arg1, double arg2, double arg3);
    boolean testAab(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5);
    org.joml.Matrix4d obliqueZ(double arg0, double arg1, org.joml.Matrix4d arg2);
    org.joml.Matrix4d withLookAtUp(org.joml.Vector3dc arg0, org.joml.Matrix4d arg1);
    org.joml.Matrix4d withLookAtUp(double arg0, double arg1, double arg2, org.joml.Matrix4d arg3);
    org.joml.Matrix4d mapXZY(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapXZnY(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapXnYnZ(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapXnZY(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapXnZnY(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapYXZ(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapYXnZ(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapYZX(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapYZnX(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapYnXZ(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapYnXnZ(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapYnZX(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapYnZnX(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapZXY(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapZXnY(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapZYX(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapZYnX(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapZnXY(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapZnXnY(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapZnYX(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapZnYnX(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapnXYnZ(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapnXZY(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapnXZnY(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapnXnYZ(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapnXnYnZ(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapnXnZY(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapnXnZnY(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapnYXZ(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapnYXnZ(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapnYZX(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapnYZnX(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapnYnXZ(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapnYnXnZ(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapnYnZX(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapnYnZnX(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapnZXY(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapnZXnY(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapnZYX(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapnZYnX(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapnZnXY(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapnZnXnY(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapnZnYX(org.joml.Matrix4d arg0);
    org.joml.Matrix4d mapnZnYnX(org.joml.Matrix4d arg0);
    org.joml.Matrix4d negateX(org.joml.Matrix4d arg0);
    org.joml.Matrix4d negateY(org.joml.Matrix4d arg0);
    org.joml.Matrix4d negateZ(org.joml.Matrix4d arg0);
    boolean equals(org.joml.Matrix4dc arg0, double arg1);
    boolean isFinite();
}
