package org.joml;

/** Auto-generated stub from paper-api-26.1.2.build.20-alpha.jar. See PLAN-FULL-STUBS.md. */
@SuppressWarnings({"unchecked", "rawtypes", "unused"})
public interface Matrix4x3dc {
    public static final int PLANE_NX = 0;
    public static final int PLANE_PX = 1;
    public static final int PLANE_NY = 2;
    public static final int PLANE_PY = 3;
    public static final int PLANE_NZ = 4;
    public static final int PLANE_PZ = 5;
    public static final byte PROPERTY_UNKNOWN = (byte) 0;
    public static final byte PROPERTY_IDENTITY = (byte) 4;
    public static final byte PROPERTY_TRANSLATION = (byte) 8;
    public static final byte PROPERTY_ORTHONORMAL = (byte) 16;
    int properties();
    double m00();
    double m01();
    double m02();
    double m10();
    double m11();
    double m12();
    double m20();
    double m21();
    double m22();
    double m30();
    double m31();
    double m32();
    org.joml.Matrix4d get(org.joml.Matrix4d arg0);
    org.joml.Matrix4x3d mul(org.joml.Matrix4x3dc arg0, org.joml.Matrix4x3d arg1);
    org.joml.Matrix4x3d mul(org.joml.Matrix4x3fc arg0, org.joml.Matrix4x3d arg1);
    org.joml.Matrix4x3d mulTranslation(org.joml.Matrix4x3dc arg0, org.joml.Matrix4x3d arg1);
    org.joml.Matrix4x3d mulTranslation(org.joml.Matrix4x3fc arg0, org.joml.Matrix4x3d arg1);
    org.joml.Matrix4x3d mulOrtho(org.joml.Matrix4x3dc arg0, org.joml.Matrix4x3d arg1);
    org.joml.Matrix4x3d mul3x3(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, double arg6, double arg7, double arg8, org.joml.Matrix4x3d arg9);
    org.joml.Matrix4x3d fma(org.joml.Matrix4x3dc arg0, double arg1, org.joml.Matrix4x3d arg2);
    org.joml.Matrix4x3d fma(org.joml.Matrix4x3fc arg0, double arg1, org.joml.Matrix4x3d arg2);
    org.joml.Matrix4x3d add(org.joml.Matrix4x3dc arg0, org.joml.Matrix4x3d arg1);
    org.joml.Matrix4x3d add(org.joml.Matrix4x3fc arg0, org.joml.Matrix4x3d arg1);
    org.joml.Matrix4x3d sub(org.joml.Matrix4x3dc arg0, org.joml.Matrix4x3d arg1);
    org.joml.Matrix4x3d sub(org.joml.Matrix4x3fc arg0, org.joml.Matrix4x3d arg1);
    org.joml.Matrix4x3d mulComponentWise(org.joml.Matrix4x3dc arg0, org.joml.Matrix4x3d arg1);
    double determinant();
    org.joml.Matrix4x3d invert(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d invertOrtho(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d transpose3x3(org.joml.Matrix4x3d arg0);
    org.joml.Matrix3d transpose3x3(org.joml.Matrix3d arg0);
    org.joml.Vector3d getTranslation(org.joml.Vector3d arg0);
    org.joml.Vector3d getScale(org.joml.Vector3d arg0);
    org.joml.Matrix4x3d get(org.joml.Matrix4x3d arg0);
    org.joml.Quaternionf getUnnormalizedRotation(org.joml.Quaternionf arg0);
    org.joml.Quaternionf getNormalizedRotation(org.joml.Quaternionf arg0);
    org.joml.Quaterniond getUnnormalizedRotation(org.joml.Quaterniond arg0);
    org.joml.Quaterniond getNormalizedRotation(org.joml.Quaterniond arg0);
    java.nio.DoubleBuffer get(java.nio.DoubleBuffer arg0);
    java.nio.DoubleBuffer get(int arg0, java.nio.DoubleBuffer arg1);
    java.nio.FloatBuffer get(java.nio.FloatBuffer arg0);
    java.nio.FloatBuffer get(int arg0, java.nio.FloatBuffer arg1);
    java.nio.ByteBuffer get(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer get(int arg0, java.nio.ByteBuffer arg1);
    java.nio.ByteBuffer getFloats(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer getFloats(int arg0, java.nio.ByteBuffer arg1);
    org.joml.Matrix4x3dc getToAddress(long arg0);
    org.joml.Matrix4x3dc getTransposedToAddress(long arg0);
    double[] get(double[] arg0, int arg1);
    double[] get(double[] arg0);
    float[] get(float[] arg0, int arg1);
    float[] get(float[] arg0);
    double[] get4x4(double[] arg0, int arg1);
    double[] get4x4(double[] arg0);
    float[] get4x4(float[] arg0, int arg1);
    float[] get4x4(float[] arg0);
    java.nio.DoubleBuffer get4x4(java.nio.DoubleBuffer arg0);
    java.nio.DoubleBuffer get4x4(int arg0, java.nio.DoubleBuffer arg1);
    java.nio.ByteBuffer get4x4(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer get4x4(int arg0, java.nio.ByteBuffer arg1);
    java.nio.DoubleBuffer getTransposed(java.nio.DoubleBuffer arg0);
    java.nio.DoubleBuffer getTransposed(int arg0, java.nio.DoubleBuffer arg1);
    java.nio.ByteBuffer getTransposed(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer getTransposed(int arg0, java.nio.ByteBuffer arg1);
    java.nio.FloatBuffer getTransposed(java.nio.FloatBuffer arg0);
    java.nio.FloatBuffer getTransposed(int arg0, java.nio.FloatBuffer arg1);
    java.nio.ByteBuffer getTransposedFloats(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer getTransposedFloats(int arg0, java.nio.ByteBuffer arg1);
    double[] getTransposed(double[] arg0, int arg1);
    double[] getTransposed(double[] arg0);
    org.joml.Vector4d transform(org.joml.Vector4d arg0);
    org.joml.Vector4d transform(org.joml.Vector4dc arg0, org.joml.Vector4d arg1);
    org.joml.Vector3d transformPosition(org.joml.Vector3d arg0);
    org.joml.Vector3d transformPosition(org.joml.Vector3dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d transformDirection(org.joml.Vector3d arg0);
    org.joml.Vector3d transformDirection(org.joml.Vector3dc arg0, org.joml.Vector3d arg1);
    org.joml.Matrix4x3d scale(org.joml.Vector3dc arg0, org.joml.Matrix4x3d arg1);
    org.joml.Matrix4x3d scale(double arg0, double arg1, double arg2, org.joml.Matrix4x3d arg3);
    org.joml.Matrix4x3d scale(double arg0, org.joml.Matrix4x3d arg1);
    org.joml.Matrix4x3d scaleXY(double arg0, double arg1, org.joml.Matrix4x3d arg2);
    org.joml.Matrix4x3d scaleAround(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, org.joml.Matrix4x3d arg6);
    org.joml.Matrix4x3d scaleAround(double arg0, double arg1, double arg2, double arg3, org.joml.Matrix4x3d arg4);
    org.joml.Matrix4x3d scaleLocal(double arg0, double arg1, double arg2, org.joml.Matrix4x3d arg3);
    org.joml.Matrix4x3d rotate(double arg0, double arg1, double arg2, double arg3, org.joml.Matrix4x3d arg4);
    org.joml.Matrix4x3d rotateTranslation(double arg0, double arg1, double arg2, double arg3, org.joml.Matrix4x3d arg4);
    org.joml.Matrix4x3d rotateAround(org.joml.Quaterniondc arg0, double arg1, double arg2, double arg3, org.joml.Matrix4x3d arg4);
    org.joml.Matrix4x3d rotateLocal(double arg0, double arg1, double arg2, double arg3, org.joml.Matrix4x3d arg4);
    org.joml.Matrix4x3d translate(org.joml.Vector3dc arg0, org.joml.Matrix4x3d arg1);
    org.joml.Matrix4x3d translate(org.joml.Vector3fc arg0, org.joml.Matrix4x3d arg1);
    org.joml.Matrix4x3d translate(double arg0, double arg1, double arg2, org.joml.Matrix4x3d arg3);
    org.joml.Matrix4x3d translateLocal(org.joml.Vector3fc arg0, org.joml.Matrix4x3d arg1);
    org.joml.Matrix4x3d translateLocal(org.joml.Vector3dc arg0, org.joml.Matrix4x3d arg1);
    org.joml.Matrix4x3d translateLocal(double arg0, double arg1, double arg2, org.joml.Matrix4x3d arg3);
    org.joml.Matrix4x3d rotateX(double arg0, org.joml.Matrix4x3d arg1);
    org.joml.Matrix4x3d rotateY(double arg0, org.joml.Matrix4x3d arg1);
    org.joml.Matrix4x3d rotateZ(double arg0, org.joml.Matrix4x3d arg1);
    org.joml.Matrix4x3d rotateXYZ(double arg0, double arg1, double arg2, org.joml.Matrix4x3d arg3);
    org.joml.Matrix4x3d rotateZYX(double arg0, double arg1, double arg2, org.joml.Matrix4x3d arg3);
    org.joml.Matrix4x3d rotateYXZ(double arg0, double arg1, double arg2, org.joml.Matrix4x3d arg3);
    org.joml.Matrix4x3d rotate(org.joml.Quaterniondc arg0, org.joml.Matrix4x3d arg1);
    org.joml.Matrix4x3d rotate(org.joml.Quaternionfc arg0, org.joml.Matrix4x3d arg1);
    org.joml.Matrix4x3d rotateTranslation(org.joml.Quaterniondc arg0, org.joml.Matrix4x3d arg1);
    org.joml.Matrix4x3d rotateTranslation(org.joml.Quaternionfc arg0, org.joml.Matrix4x3d arg1);
    org.joml.Matrix4x3d rotateLocal(org.joml.Quaterniondc arg0, org.joml.Matrix4x3d arg1);
    org.joml.Matrix4x3d rotateLocal(org.joml.Quaternionfc arg0, org.joml.Matrix4x3d arg1);
    org.joml.Matrix4x3d rotate(org.joml.AxisAngle4f arg0, org.joml.Matrix4x3d arg1);
    org.joml.Matrix4x3d rotate(org.joml.AxisAngle4d arg0, org.joml.Matrix4x3d arg1);
    org.joml.Matrix4x3d rotate(double arg0, org.joml.Vector3dc arg1, org.joml.Matrix4x3d arg2);
    org.joml.Matrix4x3d rotate(double arg0, org.joml.Vector3fc arg1, org.joml.Matrix4x3d arg2);
    org.joml.Vector4d getRow(int arg0, org.joml.Vector4d arg1) throws java.lang.IndexOutOfBoundsException;
    org.joml.Vector3d getColumn(int arg0, org.joml.Vector3d arg1) throws java.lang.IndexOutOfBoundsException;
    org.joml.Matrix4x3d normal(org.joml.Matrix4x3d arg0);
    org.joml.Matrix3d normal(org.joml.Matrix3d arg0);
    org.joml.Matrix3d cofactor3x3(org.joml.Matrix3d arg0);
    org.joml.Matrix4x3d cofactor3x3(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d normalize3x3(org.joml.Matrix4x3d arg0);
    org.joml.Matrix3d normalize3x3(org.joml.Matrix3d arg0);
    org.joml.Matrix4x3d reflect(double arg0, double arg1, double arg2, double arg3, org.joml.Matrix4x3d arg4);
    org.joml.Matrix4x3d reflect(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, org.joml.Matrix4x3d arg6);
    org.joml.Matrix4x3d reflect(org.joml.Quaterniondc arg0, org.joml.Vector3dc arg1, org.joml.Matrix4x3d arg2);
    org.joml.Matrix4x3d reflect(org.joml.Vector3dc arg0, org.joml.Vector3dc arg1, org.joml.Matrix4x3d arg2);
    org.joml.Matrix4x3d ortho(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, boolean arg6, org.joml.Matrix4x3d arg7);
    org.joml.Matrix4x3d ortho(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, org.joml.Matrix4x3d arg6);
    org.joml.Matrix4x3d orthoLH(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, boolean arg6, org.joml.Matrix4x3d arg7);
    org.joml.Matrix4x3d orthoLH(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, org.joml.Matrix4x3d arg6);
    org.joml.Matrix4x3d orthoSymmetric(double arg0, double arg1, double arg2, double arg3, boolean arg4, org.joml.Matrix4x3d arg5);
    org.joml.Matrix4x3d orthoSymmetric(double arg0, double arg1, double arg2, double arg3, org.joml.Matrix4x3d arg4);
    org.joml.Matrix4x3d orthoSymmetricLH(double arg0, double arg1, double arg2, double arg3, boolean arg4, org.joml.Matrix4x3d arg5);
    org.joml.Matrix4x3d orthoSymmetricLH(double arg0, double arg1, double arg2, double arg3, org.joml.Matrix4x3d arg4);
    org.joml.Matrix4x3d ortho2D(double arg0, double arg1, double arg2, double arg3, org.joml.Matrix4x3d arg4);
    org.joml.Matrix4x3d ortho2DLH(double arg0, double arg1, double arg2, double arg3, org.joml.Matrix4x3d arg4);
    org.joml.Matrix4x3d lookAlong(org.joml.Vector3dc arg0, org.joml.Vector3dc arg1, org.joml.Matrix4x3d arg2);
    org.joml.Matrix4x3d lookAlong(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, org.joml.Matrix4x3d arg6);
    org.joml.Matrix4x3d lookAt(org.joml.Vector3dc arg0, org.joml.Vector3dc arg1, org.joml.Vector3dc arg2, org.joml.Matrix4x3d arg3);
    org.joml.Matrix4x3d lookAt(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, double arg6, double arg7, double arg8, org.joml.Matrix4x3d arg9);
    org.joml.Matrix4x3d lookAtLH(org.joml.Vector3dc arg0, org.joml.Vector3dc arg1, org.joml.Vector3dc arg2, org.joml.Matrix4x3d arg3);
    org.joml.Matrix4x3d lookAtLH(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, double arg6, double arg7, double arg8, org.joml.Matrix4x3d arg9);
    org.joml.Vector4d frustumPlane(int arg0, org.joml.Vector4d arg1);
    org.joml.Vector3d positiveZ(org.joml.Vector3d arg0);
    org.joml.Vector3d normalizedPositiveZ(org.joml.Vector3d arg0);
    org.joml.Vector3d positiveX(org.joml.Vector3d arg0);
    org.joml.Vector3d normalizedPositiveX(org.joml.Vector3d arg0);
    org.joml.Vector3d positiveY(org.joml.Vector3d arg0);
    org.joml.Vector3d normalizedPositiveY(org.joml.Vector3d arg0);
    org.joml.Vector3d origin(org.joml.Vector3d arg0);
    org.joml.Matrix4x3d shadow(org.joml.Vector4dc arg0, double arg1, double arg2, double arg3, double arg4, org.joml.Matrix4x3d arg5);
    org.joml.Matrix4x3d shadow(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, double arg6, double arg7, org.joml.Matrix4x3d arg8);
    org.joml.Matrix4x3d shadow(org.joml.Vector4dc arg0, org.joml.Matrix4x3dc arg1, org.joml.Matrix4x3d arg2);
    org.joml.Matrix4x3d shadow(double arg0, double arg1, double arg2, double arg3, org.joml.Matrix4x3dc arg4, org.joml.Matrix4x3d arg5);
    org.joml.Matrix4x3d pick(double arg0, double arg1, double arg2, double arg3, int[] arg4, org.joml.Matrix4x3d arg5);
    org.joml.Matrix4x3d arcball(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, org.joml.Matrix4x3d arg6);
    org.joml.Matrix4x3d arcball(double arg0, org.joml.Vector3dc arg1, double arg2, double arg3, org.joml.Matrix4x3d arg4);
    org.joml.Matrix4x3d transformAab(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, org.joml.Vector3d arg6, org.joml.Vector3d arg7);
    org.joml.Matrix4x3d transformAab(org.joml.Vector3dc arg0, org.joml.Vector3dc arg1, org.joml.Vector3d arg2, org.joml.Vector3d arg3);
    org.joml.Matrix4x3d lerp(org.joml.Matrix4x3dc arg0, double arg1, org.joml.Matrix4x3d arg2);
    org.joml.Matrix4x3d rotateTowards(org.joml.Vector3dc arg0, org.joml.Vector3dc arg1, org.joml.Matrix4x3d arg2);
    org.joml.Matrix4x3d rotateTowards(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, org.joml.Matrix4x3d arg6);
    org.joml.Vector3d getEulerAnglesXYZ(org.joml.Vector3d arg0);
    org.joml.Vector3d getEulerAnglesZYX(org.joml.Vector3d arg0);
    org.joml.Vector3d getEulerAnglesYXZ(org.joml.Vector3d arg0);
    org.joml.Matrix4x3d obliqueZ(double arg0, double arg1, org.joml.Matrix4x3d arg2);
    org.joml.Matrix4x3d mapXZY(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapXZnY(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapXnYnZ(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapXnZY(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapXnZnY(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapYXZ(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapYXnZ(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapYZX(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapYZnX(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapYnXZ(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapYnXnZ(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapYnZX(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapYnZnX(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapZXY(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapZXnY(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapZYX(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapZYnX(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapZnXY(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapZnXnY(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapZnYX(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapZnYnX(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapnXYnZ(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapnXZY(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapnXZnY(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapnXnYZ(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapnXnYnZ(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapnXnZY(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapnXnZnY(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapnYXZ(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapnYXnZ(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapnYZX(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapnYZnX(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapnYnXZ(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapnYnXnZ(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapnYnZX(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapnYnZnX(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapnZXY(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapnZXnY(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapnZYX(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapnZYnX(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapnZnXY(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapnZnXnY(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapnZnYX(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d mapnZnYnX(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d negateX(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d negateY(org.joml.Matrix4x3d arg0);
    org.joml.Matrix4x3d negateZ(org.joml.Matrix4x3d arg0);
    boolean equals(org.joml.Matrix4x3dc arg0, double arg1);
    boolean isFinite();
}
