package org.joml;

/** Auto-generated stub from paper-api-26.1.2.build.20-alpha.jar. See PLAN-FULL-STUBS.md. */
@SuppressWarnings({"unchecked", "rawtypes", "unused"})
public interface Matrix4x3fc {
    public static final int PLANE_NX = 0;
    public static final int PLANE_PX = 1;
    public static final int PLANE_NY = 2;
    public static final int PLANE_PY = 3;
    public static final int PLANE_NZ = 4;
    public static final int PLANE_PZ = 5;
    public static final byte PROPERTY_UNKNOWN = (byte) 0;
    public static final byte PROPERTY_IDENTITY = (byte) 4;
    public static final byte PROPERTY_TRANSLATION = (byte) 8;
    public static final byte PROPERTY_ORTHONORMAL = (byte) 16;
    int properties();
    float m00();
    float m01();
    float m02();
    float m10();
    float m11();
    float m12();
    float m20();
    float m21();
    float m22();
    float m30();
    float m31();
    float m32();
    org.joml.Matrix4f get(org.joml.Matrix4f arg0);
    org.joml.Matrix4d get(org.joml.Matrix4d arg0);
    org.joml.Matrix4x3f mul(org.joml.Matrix4x3fc arg0, org.joml.Matrix4x3f arg1);
    org.joml.Matrix4x3f mulTranslation(org.joml.Matrix4x3fc arg0, org.joml.Matrix4x3f arg1);
    org.joml.Matrix4x3f mulOrtho(org.joml.Matrix4x3fc arg0, org.joml.Matrix4x3f arg1);
    org.joml.Matrix4x3f mul3x3(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, float arg6, float arg7, float arg8, org.joml.Matrix4x3f arg9);
    org.joml.Matrix4x3f fma(org.joml.Matrix4x3fc arg0, float arg1, org.joml.Matrix4x3f arg2);
    org.joml.Matrix4x3f add(org.joml.Matrix4x3fc arg0, org.joml.Matrix4x3f arg1);
    org.joml.Matrix4x3f sub(org.joml.Matrix4x3fc arg0, org.joml.Matrix4x3f arg1);
    org.joml.Matrix4x3f mulComponentWise(org.joml.Matrix4x3fc arg0, org.joml.Matrix4x3f arg1);
    float determinant();
    org.joml.Matrix4x3f invert(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4f invert(org.joml.Matrix4f arg0);
    org.joml.Matrix4x3f invertOrtho(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f transpose3x3(org.joml.Matrix4x3f arg0);
    org.joml.Matrix3f transpose3x3(org.joml.Matrix3f arg0);
    org.joml.Vector3f getTranslation(org.joml.Vector3f arg0);
    org.joml.Vector3f getScale(org.joml.Vector3f arg0);
    org.joml.Matrix4x3f get(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3d get(org.joml.Matrix4x3d arg0);
    org.joml.AxisAngle4f getRotation(org.joml.AxisAngle4f arg0);
    org.joml.AxisAngle4d getRotation(org.joml.AxisAngle4d arg0);
    org.joml.Quaternionf getUnnormalizedRotation(org.joml.Quaternionf arg0);
    org.joml.Quaternionf getNormalizedRotation(org.joml.Quaternionf arg0);
    org.joml.Quaterniond getUnnormalizedRotation(org.joml.Quaterniond arg0);
    org.joml.Quaterniond getNormalizedRotation(org.joml.Quaterniond arg0);
    java.nio.FloatBuffer get(java.nio.FloatBuffer arg0);
    java.nio.FloatBuffer get(int arg0, java.nio.FloatBuffer arg1);
    java.nio.ByteBuffer get(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer get(int arg0, java.nio.ByteBuffer arg1);
    org.joml.Matrix4x3fc getToAddress(long arg0);
    org.joml.Matrix4x3fc getTransposedToAddress(long arg0);
    float[] get(float[] arg0, int arg1);
    float[] get(float[] arg0);
    float[] get4x4(float[] arg0, int arg1);
    float[] get4x4(float[] arg0);
    java.nio.FloatBuffer get4x4(java.nio.FloatBuffer arg0);
    java.nio.FloatBuffer get4x4(int arg0, java.nio.FloatBuffer arg1);
    java.nio.ByteBuffer get4x4(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer get4x4(int arg0, java.nio.ByteBuffer arg1);
    java.nio.FloatBuffer get3x4(java.nio.FloatBuffer arg0);
    java.nio.FloatBuffer get3x4(int arg0, java.nio.FloatBuffer arg1);
    java.nio.ByteBuffer get3x4(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer get3x4(int arg0, java.nio.ByteBuffer arg1);
    java.nio.FloatBuffer getTransposed(java.nio.FloatBuffer arg0);
    java.nio.FloatBuffer getTransposed(int arg0, java.nio.FloatBuffer arg1);
    java.nio.ByteBuffer getTransposed(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer getTransposed(int arg0, java.nio.ByteBuffer arg1);
    float[] getTransposed(float[] arg0, int arg1);
    float[] getTransposed(float[] arg0);
    org.joml.Vector4f transform(org.joml.Vector4f arg0);
    org.joml.Vector4f transform(org.joml.Vector4fc arg0, org.joml.Vector4f arg1);
    org.joml.Vector3f transformPosition(org.joml.Vector3f arg0);
    org.joml.Vector3f transformPosition(org.joml.Vector3fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f transformDirection(org.joml.Vector3f arg0);
    org.joml.Vector3f transformDirection(org.joml.Vector3fc arg0, org.joml.Vector3f arg1);
    org.joml.Matrix4x3f scale(org.joml.Vector3fc arg0, org.joml.Matrix4x3f arg1);
    org.joml.Matrix4x3f scale(float arg0, org.joml.Matrix4x3f arg1);
    org.joml.Matrix4x3f scaleXY(float arg0, float arg1, org.joml.Matrix4x3f arg2);
    org.joml.Matrix4x3f scaleAround(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, org.joml.Matrix4x3f arg6);
    org.joml.Matrix4x3f scaleAround(float arg0, float arg1, float arg2, float arg3, org.joml.Matrix4x3f arg4);
    org.joml.Matrix4x3f scale(float arg0, float arg1, float arg2, org.joml.Matrix4x3f arg3);
    org.joml.Matrix4x3f scaleLocal(float arg0, float arg1, float arg2, org.joml.Matrix4x3f arg3);
    org.joml.Matrix4x3f rotateX(float arg0, org.joml.Matrix4x3f arg1);
    org.joml.Matrix4x3f rotateY(float arg0, org.joml.Matrix4x3f arg1);
    org.joml.Matrix4x3f rotateZ(float arg0, org.joml.Matrix4x3f arg1);
    org.joml.Matrix4x3f rotateXYZ(float arg0, float arg1, float arg2, org.joml.Matrix4x3f arg3);
    org.joml.Matrix4x3f rotateZYX(float arg0, float arg1, float arg2, org.joml.Matrix4x3f arg3);
    org.joml.Matrix4x3f rotateYXZ(float arg0, float arg1, float arg2, org.joml.Matrix4x3f arg3);
    org.joml.Matrix4x3f rotate(float arg0, float arg1, float arg2, float arg3, org.joml.Matrix4x3f arg4);
    org.joml.Matrix4x3f rotateTranslation(float arg0, float arg1, float arg2, float arg3, org.joml.Matrix4x3f arg4);
    org.joml.Matrix4x3f rotateAround(org.joml.Quaternionfc arg0, float arg1, float arg2, float arg3, org.joml.Matrix4x3f arg4);
    org.joml.Matrix4x3f rotateLocal(float arg0, float arg1, float arg2, float arg3, org.joml.Matrix4x3f arg4);
    org.joml.Matrix4x3f translate(org.joml.Vector3fc arg0, org.joml.Matrix4x3f arg1);
    org.joml.Matrix4x3f translate(float arg0, float arg1, float arg2, org.joml.Matrix4x3f arg3);
    org.joml.Matrix4x3f translateLocal(org.joml.Vector3fc arg0, org.joml.Matrix4x3f arg1);
    org.joml.Matrix4x3f translateLocal(float arg0, float arg1, float arg2, org.joml.Matrix4x3f arg3);
    org.joml.Matrix4x3f ortho(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, boolean arg6, org.joml.Matrix4x3f arg7);
    org.joml.Matrix4x3f ortho(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, org.joml.Matrix4x3f arg6);
    org.joml.Matrix4x3f orthoLH(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, boolean arg6, org.joml.Matrix4x3f arg7);
    org.joml.Matrix4x3f orthoLH(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, org.joml.Matrix4x3f arg6);
    org.joml.Matrix4x3f orthoSymmetric(float arg0, float arg1, float arg2, float arg3, boolean arg4, org.joml.Matrix4x3f arg5);
    org.joml.Matrix4x3f orthoSymmetric(float arg0, float arg1, float arg2, float arg3, org.joml.Matrix4x3f arg4);
    org.joml.Matrix4x3f orthoSymmetricLH(float arg0, float arg1, float arg2, float arg3, boolean arg4, org.joml.Matrix4x3f arg5);
    org.joml.Matrix4x3f orthoSymmetricLH(float arg0, float arg1, float arg2, float arg3, org.joml.Matrix4x3f arg4);
    org.joml.Matrix4x3f ortho2D(float arg0, float arg1, float arg2, float arg3, org.joml.Matrix4x3f arg4);
    org.joml.Matrix4x3f ortho2DLH(float arg0, float arg1, float arg2, float arg3, org.joml.Matrix4x3f arg4);
    org.joml.Matrix4x3f lookAlong(org.joml.Vector3fc arg0, org.joml.Vector3fc arg1, org.joml.Matrix4x3f arg2);
    org.joml.Matrix4x3f lookAlong(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, org.joml.Matrix4x3f arg6);
    org.joml.Matrix4x3f lookAt(org.joml.Vector3fc arg0, org.joml.Vector3fc arg1, org.joml.Vector3fc arg2, org.joml.Matrix4x3f arg3);
    org.joml.Matrix4x3f lookAt(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, float arg6, float arg7, float arg8, org.joml.Matrix4x3f arg9);
    org.joml.Matrix4x3f lookAtLH(org.joml.Vector3fc arg0, org.joml.Vector3fc arg1, org.joml.Vector3fc arg2, org.joml.Matrix4x3f arg3);
    org.joml.Matrix4x3f lookAtLH(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, float arg6, float arg7, float arg8, org.joml.Matrix4x3f arg9);
    org.joml.Matrix4x3f rotate(org.joml.Quaternionfc arg0, org.joml.Matrix4x3f arg1);
    org.joml.Matrix4x3f rotateTranslation(org.joml.Quaternionfc arg0, org.joml.Matrix4x3f arg1);
    org.joml.Matrix4x3f rotateLocal(org.joml.Quaternionfc arg0, org.joml.Matrix4x3f arg1);
    org.joml.Matrix4x3f rotate(org.joml.AxisAngle4f arg0, org.joml.Matrix4x3f arg1);
    org.joml.Matrix4x3f rotate(float arg0, org.joml.Vector3fc arg1, org.joml.Matrix4x3f arg2);
    org.joml.Matrix4x3f reflect(float arg0, float arg1, float arg2, float arg3, org.joml.Matrix4x3f arg4);
    org.joml.Matrix4x3f reflect(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, org.joml.Matrix4x3f arg6);
    org.joml.Matrix4x3f reflect(org.joml.Quaternionfc arg0, org.joml.Vector3fc arg1, org.joml.Matrix4x3f arg2);
    org.joml.Matrix4x3f reflect(org.joml.Vector3fc arg0, org.joml.Vector3fc arg1, org.joml.Matrix4x3f arg2);
    org.joml.Vector4f getRow(int arg0, org.joml.Vector4f arg1) throws java.lang.IndexOutOfBoundsException;
    org.joml.Vector3f getColumn(int arg0, org.joml.Vector3f arg1) throws java.lang.IndexOutOfBoundsException;
    org.joml.Matrix4x3f normal(org.joml.Matrix4x3f arg0);
    org.joml.Matrix3f normal(org.joml.Matrix3f arg0);
    org.joml.Matrix3f cofactor3x3(org.joml.Matrix3f arg0);
    org.joml.Matrix4x3f cofactor3x3(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f normalize3x3(org.joml.Matrix4x3f arg0);
    org.joml.Matrix3f normalize3x3(org.joml.Matrix3f arg0);
    org.joml.Vector4f frustumPlane(int arg0, org.joml.Vector4f arg1);
    org.joml.Vector3f positiveZ(org.joml.Vector3f arg0);
    org.joml.Vector3f normalizedPositiveZ(org.joml.Vector3f arg0);
    org.joml.Vector3f positiveX(org.joml.Vector3f arg0);
    org.joml.Vector3f normalizedPositiveX(org.joml.Vector3f arg0);
    org.joml.Vector3f positiveY(org.joml.Vector3f arg0);
    org.joml.Vector3f normalizedPositiveY(org.joml.Vector3f arg0);
    org.joml.Vector3f origin(org.joml.Vector3f arg0);
    org.joml.Matrix4x3f shadow(org.joml.Vector4fc arg0, float arg1, float arg2, float arg3, float arg4, org.joml.Matrix4x3f arg5);
    org.joml.Matrix4x3f shadow(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, float arg6, float arg7, org.joml.Matrix4x3f arg8);
    org.joml.Matrix4x3f shadow(org.joml.Vector4fc arg0, org.joml.Matrix4x3fc arg1, org.joml.Matrix4x3f arg2);
    org.joml.Matrix4x3f shadow(float arg0, float arg1, float arg2, float arg3, org.joml.Matrix4x3fc arg4, org.joml.Matrix4x3f arg5);
    org.joml.Matrix4x3f pick(float arg0, float arg1, float arg2, float arg3, int[] arg4, org.joml.Matrix4x3f arg5);
    org.joml.Matrix4x3f arcball(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, org.joml.Matrix4x3f arg6);
    org.joml.Matrix4x3f arcball(float arg0, org.joml.Vector3fc arg1, float arg2, float arg3, org.joml.Matrix4x3f arg4);
    org.joml.Matrix4x3f transformAab(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, org.joml.Vector3f arg6, org.joml.Vector3f arg7);
    org.joml.Matrix4x3f transformAab(org.joml.Vector3fc arg0, org.joml.Vector3fc arg1, org.joml.Vector3f arg2, org.joml.Vector3f arg3);
    org.joml.Matrix4x3f lerp(org.joml.Matrix4x3fc arg0, float arg1, org.joml.Matrix4x3f arg2);
    org.joml.Matrix4x3f rotateTowards(org.joml.Vector3fc arg0, org.joml.Vector3fc arg1, org.joml.Matrix4x3f arg2);
    org.joml.Matrix4x3f rotateTowards(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, org.joml.Matrix4x3f arg6);
    org.joml.Vector3f getEulerAnglesXYZ(org.joml.Vector3f arg0);
    org.joml.Vector3f getEulerAnglesZYX(org.joml.Vector3f arg0);
    org.joml.Vector3f getEulerAnglesYXZ(org.joml.Vector3f arg0);
    org.joml.Matrix4x3f obliqueZ(float arg0, float arg1, org.joml.Matrix4x3f arg2);
    org.joml.Matrix4x3f withLookAtUp(org.joml.Vector3fc arg0, org.joml.Matrix4x3f arg1);
    org.joml.Matrix4x3f withLookAtUp(float arg0, float arg1, float arg2, org.joml.Matrix4x3f arg3);
    org.joml.Matrix4x3f mapXZY(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapXZnY(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapXnYnZ(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapXnZY(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapXnZnY(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapYXZ(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapYXnZ(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapYZX(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapYZnX(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapYnXZ(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapYnXnZ(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapYnZX(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapYnZnX(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapZXY(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapZXnY(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapZYX(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapZYnX(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapZnXY(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapZnXnY(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapZnYX(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapZnYnX(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapnXYnZ(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapnXZY(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapnXZnY(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapnXnYZ(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapnXnYnZ(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapnXnZY(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapnXnZnY(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapnYXZ(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapnYXnZ(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapnYZX(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapnYZnX(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapnYnXZ(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapnYnXnZ(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapnYnZX(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapnYnZnX(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapnZXY(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapnZXnY(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapnZYX(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapnZYnX(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapnZnXY(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapnZnXnY(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapnZnYX(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f mapnZnYnX(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f negateX(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f negateY(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3f negateZ(org.joml.Matrix4x3f arg0);
    boolean equals(org.joml.Matrix4x3fc arg0, float arg1);
    boolean isFinite();
}
