package org.joml;

/** Auto-generated stub from paper-api-26.1.2.build.20-alpha.jar. See PLAN-FULL-STUBS.md. */
@SuppressWarnings({"unchecked", "rawtypes", "unused"})
public interface Matrix3fc {
    float m00();
    float m01();
    float m02();
    float m10();
    float m11();
    float m12();
    float m20();
    float m21();
    float m22();
    org.joml.Matrix3f mul(org.joml.Matrix3fc arg0, org.joml.Matrix3f arg1);
    org.joml.Matrix3f mulLocal(org.joml.Matrix3fc arg0, org.joml.Matrix3f arg1);
    float determinant();
    org.joml.Matrix3f invert(org.joml.Matrix3f arg0);
    org.joml.Matrix3f transpose(org.joml.Matrix3f arg0);
    org.joml.Matrix3f get(org.joml.Matrix3f arg0);
    org.joml.Matrix4f get(org.joml.Matrix4f arg0);
    org.joml.AxisAngle4f getRotation(org.joml.AxisAngle4f arg0);
    org.joml.Quaternionf getUnnormalizedRotation(org.joml.Quaternionf arg0);
    org.joml.Quaternionf getNormalizedRotation(org.joml.Quaternionf arg0);
    org.joml.Quaterniond getUnnormalizedRotation(org.joml.Quaterniond arg0);
    org.joml.Quaterniond getNormalizedRotation(org.joml.Quaterniond arg0);
    java.nio.FloatBuffer get(java.nio.FloatBuffer arg0);
    java.nio.FloatBuffer get(int arg0, java.nio.FloatBuffer arg1);
    java.nio.ByteBuffer get(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer get(int arg0, java.nio.ByteBuffer arg1);
    java.nio.FloatBuffer get3x4(java.nio.FloatBuffer arg0);
    java.nio.FloatBuffer get3x4(int arg0, java.nio.FloatBuffer arg1);
    java.nio.ByteBuffer get3x4(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer get3x4(int arg0, java.nio.ByteBuffer arg1);
    java.nio.FloatBuffer getTransposed(java.nio.FloatBuffer arg0);
    java.nio.FloatBuffer getTransposed(int arg0, java.nio.FloatBuffer arg1);
    java.nio.ByteBuffer getTransposed(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer getTransposed(int arg0, java.nio.ByteBuffer arg1);
    org.joml.Matrix3fc getToAddress(long arg0);
    org.joml.Matrix3fc getTransposedToAddress(long arg0);
    float[] get(float[] arg0, int arg1);
    float[] get(float[] arg0);
    org.joml.Matrix3f scale(org.joml.Vector3fc arg0, org.joml.Matrix3f arg1);
    org.joml.Matrix3f scale(float arg0, float arg1, float arg2, org.joml.Matrix3f arg3);
    org.joml.Matrix3f scale(float arg0, org.joml.Matrix3f arg1);
    org.joml.Matrix3f scaleLocal(float arg0, float arg1, float arg2, org.joml.Matrix3f arg3);
    org.joml.Vector3f transform(org.joml.Vector3f arg0);
    org.joml.Vector3f transform(org.joml.Vector3fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f transform(float arg0, float arg1, float arg2, org.joml.Vector3f arg3);
    org.joml.Vector3f transformTranspose(org.joml.Vector3f arg0);
    org.joml.Vector3f transformTranspose(org.joml.Vector3fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f transformTranspose(float arg0, float arg1, float arg2, org.joml.Vector3f arg3);
    org.joml.Matrix3f rotateX(float arg0, org.joml.Matrix3f arg1);
    org.joml.Matrix3f rotateY(float arg0, org.joml.Matrix3f arg1);
    org.joml.Matrix3f rotateZ(float arg0, org.joml.Matrix3f arg1);
    org.joml.Matrix3f rotateXYZ(float arg0, float arg1, float arg2, org.joml.Matrix3f arg3);
    org.joml.Matrix3f rotateZYX(float arg0, float arg1, float arg2, org.joml.Matrix3f arg3);
    org.joml.Matrix3f rotateYXZ(float arg0, float arg1, float arg2, org.joml.Matrix3f arg3);
    org.joml.Matrix3f rotate(float arg0, float arg1, float arg2, float arg3, org.joml.Matrix3f arg4);
    org.joml.Matrix3f rotateLocal(float arg0, float arg1, float arg2, float arg3, org.joml.Matrix3f arg4);
    org.joml.Matrix3f rotateLocalX(float arg0, org.joml.Matrix3f arg1);
    org.joml.Matrix3f rotateLocalY(float arg0, org.joml.Matrix3f arg1);
    org.joml.Matrix3f rotateLocalZ(float arg0, org.joml.Matrix3f arg1);
    org.joml.Matrix3f rotate(org.joml.Quaternionfc arg0, org.joml.Matrix3f arg1);
    org.joml.Matrix3f rotateLocal(org.joml.Quaternionfc arg0, org.joml.Matrix3f arg1);
    org.joml.Matrix3f rotate(org.joml.AxisAngle4f arg0, org.joml.Matrix3f arg1);
    org.joml.Matrix3f rotate(float arg0, org.joml.Vector3fc arg1, org.joml.Matrix3f arg2);
    org.joml.Matrix3f lookAlong(org.joml.Vector3fc arg0, org.joml.Vector3fc arg1, org.joml.Matrix3f arg2);
    org.joml.Matrix3f lookAlong(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, org.joml.Matrix3f arg6);
    org.joml.Vector3f getRow(int arg0, org.joml.Vector3f arg1) throws java.lang.IndexOutOfBoundsException;
    org.joml.Vector3f getColumn(int arg0, org.joml.Vector3f arg1) throws java.lang.IndexOutOfBoundsException;
    float get(int arg0, int arg1);
    float getRowColumn(int arg0, int arg1);
    org.joml.Matrix3f normal(org.joml.Matrix3f arg0);
    org.joml.Matrix3f cofactor(org.joml.Matrix3f arg0);
    org.joml.Vector3f getScale(org.joml.Vector3f arg0);
    org.joml.Vector3f positiveZ(org.joml.Vector3f arg0);
    org.joml.Vector3f normalizedPositiveZ(org.joml.Vector3f arg0);
    org.joml.Vector3f positiveX(org.joml.Vector3f arg0);
    org.joml.Vector3f normalizedPositiveX(org.joml.Vector3f arg0);
    org.joml.Vector3f positiveY(org.joml.Vector3f arg0);
    org.joml.Vector3f normalizedPositiveY(org.joml.Vector3f arg0);
    org.joml.Matrix3f add(org.joml.Matrix3fc arg0, org.joml.Matrix3f arg1);
    org.joml.Matrix3f sub(org.joml.Matrix3fc arg0, org.joml.Matrix3f arg1);
    org.joml.Matrix3f mulComponentWise(org.joml.Matrix3fc arg0, org.joml.Matrix3f arg1);
    org.joml.Matrix3f lerp(org.joml.Matrix3fc arg0, float arg1, org.joml.Matrix3f arg2);
    org.joml.Matrix3f rotateTowards(org.joml.Vector3fc arg0, org.joml.Vector3fc arg1, org.joml.Matrix3f arg2);
    org.joml.Matrix3f rotateTowards(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, org.joml.Matrix3f arg6);
    org.joml.Vector3f getEulerAnglesXYZ(org.joml.Vector3f arg0);
    org.joml.Vector3f getEulerAnglesZYX(org.joml.Vector3f arg0);
    org.joml.Vector3f getEulerAnglesYXZ(org.joml.Vector3f arg0);
    org.joml.Matrix3f obliqueZ(float arg0, float arg1, org.joml.Matrix3f arg2);
    boolean equals(org.joml.Matrix3fc arg0, float arg1);
    org.joml.Matrix3f reflect(float arg0, float arg1, float arg2, org.joml.Matrix3f arg3);
    org.joml.Matrix3f reflect(org.joml.Quaternionfc arg0, org.joml.Matrix3f arg1);
    org.joml.Matrix3f reflect(org.joml.Vector3fc arg0, org.joml.Matrix3f arg1);
    boolean isFinite();
    float quadraticFormProduct(float arg0, float arg1, float arg2);
    float quadraticFormProduct(org.joml.Vector3fc arg0);
    org.joml.Matrix3f mapXZY(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapXZnY(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapXnYnZ(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapXnZY(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapXnZnY(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapYXZ(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapYXnZ(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapYZX(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapYZnX(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapYnXZ(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapYnXnZ(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapYnZX(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapYnZnX(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapZXY(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapZXnY(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapZYX(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapZYnX(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapZnXY(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapZnXnY(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapZnYX(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapZnYnX(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapnXYnZ(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapnXZY(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapnXZnY(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapnXnYZ(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapnXnYnZ(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapnXnZY(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapnXnZnY(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapnYXZ(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapnYXnZ(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapnYZX(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapnYZnX(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapnYnXZ(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapnYnXnZ(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapnYnZX(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapnYnZnX(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapnZXY(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapnZXnY(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapnZYX(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapnZYnX(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapnZnXY(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapnZnXnY(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapnZnYX(org.joml.Matrix3f arg0);
    org.joml.Matrix3f mapnZnYnX(org.joml.Matrix3f arg0);
    org.joml.Matrix3f negateX(org.joml.Matrix3f arg0);
    org.joml.Matrix3f negateY(org.joml.Matrix3f arg0);
    org.joml.Matrix3f negateZ(org.joml.Matrix3f arg0);
}
