package org.joml;

/** Auto-generated stub from paper-api-26.1.2.build.20-alpha.jar. See PLAN-FULL-STUBS.md. */
@SuppressWarnings({"unchecked", "rawtypes", "unused"})
public interface Matrix3dc {
    double m00();
    double m01();
    double m02();
    double m10();
    double m11();
    double m12();
    double m20();
    double m21();
    double m22();
    org.joml.Matrix3d mul(org.joml.Matrix3dc arg0, org.joml.Matrix3d arg1);
    org.joml.Matrix3d mulLocal(org.joml.Matrix3dc arg0, org.joml.Matrix3d arg1);
    org.joml.Matrix3d mul(org.joml.Matrix3fc arg0, org.joml.Matrix3d arg1);
    double determinant();
    org.joml.Matrix3d invert(org.joml.Matrix3d arg0);
    org.joml.Matrix3d transpose(org.joml.Matrix3d arg0);
    org.joml.Matrix3d get(org.joml.Matrix3d arg0);
    org.joml.AxisAngle4f getRotation(org.joml.AxisAngle4f arg0);
    org.joml.Quaternionf getUnnormalizedRotation(org.joml.Quaternionf arg0);
    org.joml.Quaternionf getNormalizedRotation(org.joml.Quaternionf arg0);
    org.joml.Quaterniond getUnnormalizedRotation(org.joml.Quaterniond arg0);
    org.joml.Quaterniond getNormalizedRotation(org.joml.Quaterniond arg0);
    java.nio.DoubleBuffer get(java.nio.DoubleBuffer arg0);
    java.nio.DoubleBuffer get(int arg0, java.nio.DoubleBuffer arg1);
    java.nio.FloatBuffer get(java.nio.FloatBuffer arg0);
    java.nio.FloatBuffer get(int arg0, java.nio.FloatBuffer arg1);
    java.nio.ByteBuffer get(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer get(int arg0, java.nio.ByteBuffer arg1);
    java.nio.ByteBuffer getFloats(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer getFloats(int arg0, java.nio.ByteBuffer arg1);
    java.nio.DoubleBuffer getTransposed(java.nio.DoubleBuffer arg0);
    java.nio.DoubleBuffer getTransposed(int arg0, java.nio.DoubleBuffer arg1);
    java.nio.ByteBuffer getTransposed(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer getTransposed(int arg0, java.nio.ByteBuffer arg1);
    java.nio.FloatBuffer getTransposed(java.nio.FloatBuffer arg0);
    java.nio.FloatBuffer getTransposed(int arg0, java.nio.FloatBuffer arg1);
    java.nio.ByteBuffer getTransposedFloats(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer getTransposedFloats(int arg0, java.nio.ByteBuffer arg1);
    org.joml.Matrix3dc getToAddress(long arg0);
    org.joml.Matrix3dc getTransposedToAddress(long arg0);
    double[] get(double[] arg0, int arg1);
    double[] get(double[] arg0);
    float[] get(float[] arg0, int arg1);
    float[] get(float[] arg0);
    org.joml.Matrix3d scale(org.joml.Vector3dc arg0, org.joml.Matrix3d arg1);
    org.joml.Matrix3d scale(double arg0, double arg1, double arg2, org.joml.Matrix3d arg3);
    org.joml.Matrix3d scale(double arg0, org.joml.Matrix3d arg1);
    org.joml.Matrix3d scaleLocal(double arg0, double arg1, double arg2, org.joml.Matrix3d arg3);
    org.joml.Vector3d transform(org.joml.Vector3d arg0);
    org.joml.Vector3d transform(org.joml.Vector3dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3f transform(org.joml.Vector3f arg0);
    org.joml.Vector3f transform(org.joml.Vector3fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3d transform(double arg0, double arg1, double arg2, org.joml.Vector3d arg3);
    org.joml.Vector3d transformTranspose(org.joml.Vector3d arg0);
    org.joml.Vector3d transformTranspose(org.joml.Vector3dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d transformTranspose(double arg0, double arg1, double arg2, org.joml.Vector3d arg3);
    org.joml.Matrix3d rotateX(double arg0, org.joml.Matrix3d arg1);
    org.joml.Matrix3d rotateY(double arg0, org.joml.Matrix3d arg1);
    org.joml.Matrix3d rotateZ(double arg0, org.joml.Matrix3d arg1);
    org.joml.Matrix3d rotateXYZ(double arg0, double arg1, double arg2, org.joml.Matrix3d arg3);
    org.joml.Matrix3d rotateZYX(double arg0, double arg1, double arg2, org.joml.Matrix3d arg3);
    org.joml.Matrix3d rotateYXZ(double arg0, double arg1, double arg2, org.joml.Matrix3d arg3);
    org.joml.Matrix3d rotate(double arg0, double arg1, double arg2, double arg3, org.joml.Matrix3d arg4);
    org.joml.Matrix3d rotateLocal(double arg0, double arg1, double arg2, double arg3, org.joml.Matrix3d arg4);
    org.joml.Matrix3d rotateLocalX(double arg0, org.joml.Matrix3d arg1);
    org.joml.Matrix3d rotateLocalY(double arg0, org.joml.Matrix3d arg1);
    org.joml.Matrix3d rotateLocalZ(double arg0, org.joml.Matrix3d arg1);
    org.joml.Matrix3d rotateLocal(org.joml.Quaterniondc arg0, org.joml.Matrix3d arg1);
    org.joml.Matrix3d rotateLocal(org.joml.Quaternionfc arg0, org.joml.Matrix3d arg1);
    org.joml.Matrix3d rotate(org.joml.Quaterniondc arg0, org.joml.Matrix3d arg1);
    org.joml.Matrix3d rotate(org.joml.Quaternionfc arg0, org.joml.Matrix3d arg1);
    org.joml.Matrix3d rotate(org.joml.AxisAngle4f arg0, org.joml.Matrix3d arg1);
    org.joml.Matrix3d rotate(org.joml.AxisAngle4d arg0, org.joml.Matrix3d arg1);
    org.joml.Matrix3d rotate(double arg0, org.joml.Vector3dc arg1, org.joml.Matrix3d arg2);
    org.joml.Matrix3d rotate(double arg0, org.joml.Vector3fc arg1, org.joml.Matrix3d arg2);
    org.joml.Vector3d getRow(int arg0, org.joml.Vector3d arg1) throws java.lang.IndexOutOfBoundsException;
    org.joml.Vector3d getColumn(int arg0, org.joml.Vector3d arg1) throws java.lang.IndexOutOfBoundsException;
    double get(int arg0, int arg1);
    double getRowColumn(int arg0, int arg1);
    org.joml.Matrix3d normal(org.joml.Matrix3d arg0);
    org.joml.Matrix3d cofactor(org.joml.Matrix3d arg0);
    org.joml.Matrix3d lookAlong(org.joml.Vector3dc arg0, org.joml.Vector3dc arg1, org.joml.Matrix3d arg2);
    org.joml.Matrix3d lookAlong(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, org.joml.Matrix3d arg6);
    org.joml.Vector3d getScale(org.joml.Vector3d arg0);
    org.joml.Vector3d positiveZ(org.joml.Vector3d arg0);
    org.joml.Vector3d normalizedPositiveZ(org.joml.Vector3d arg0);
    org.joml.Vector3d positiveX(org.joml.Vector3d arg0);
    org.joml.Vector3d normalizedPositiveX(org.joml.Vector3d arg0);
    org.joml.Vector3d positiveY(org.joml.Vector3d arg0);
    org.joml.Vector3d normalizedPositiveY(org.joml.Vector3d arg0);
    org.joml.Matrix3d add(org.joml.Matrix3dc arg0, org.joml.Matrix3d arg1);
    org.joml.Matrix3d sub(org.joml.Matrix3dc arg0, org.joml.Matrix3d arg1);
    org.joml.Matrix3d mulComponentWise(org.joml.Matrix3dc arg0, org.joml.Matrix3d arg1);
    org.joml.Matrix3d lerp(org.joml.Matrix3dc arg0, double arg1, org.joml.Matrix3d arg2);
    org.joml.Matrix3d rotateTowards(org.joml.Vector3dc arg0, org.joml.Vector3dc arg1, org.joml.Matrix3d arg2);
    org.joml.Matrix3d rotateTowards(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, org.joml.Matrix3d arg6);
    org.joml.Vector3d getEulerAnglesXYZ(org.joml.Vector3d arg0);
    org.joml.Vector3d getEulerAnglesZYX(org.joml.Vector3d arg0);
    org.joml.Vector3d getEulerAnglesYXZ(org.joml.Vector3d arg0);
    org.joml.Matrix3d obliqueZ(double arg0, double arg1, org.joml.Matrix3d arg2);
    boolean equals(org.joml.Matrix3dc arg0, double arg1);
    org.joml.Matrix3d reflect(double arg0, double arg1, double arg2, org.joml.Matrix3d arg3);
    org.joml.Matrix3d reflect(org.joml.Quaterniondc arg0, org.joml.Matrix3d arg1);
    org.joml.Matrix3d reflect(org.joml.Vector3dc arg0, org.joml.Matrix3d arg1);
    boolean isFinite();
    double quadraticFormProduct(double arg0, double arg1, double arg2);
    double quadraticFormProduct(org.joml.Vector3dc arg0);
    double quadraticFormProduct(org.joml.Vector3fc arg0);
    org.joml.Matrix3d mapXZY(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapXZnY(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapXnYnZ(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapXnZY(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapXnZnY(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapYXZ(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapYXnZ(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapYZX(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapYZnX(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapYnXZ(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapYnXnZ(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapYnZX(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapYnZnX(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapZXY(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapZXnY(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapZYX(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapZYnX(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapZnXY(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapZnXnY(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapZnYX(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapZnYnX(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapnXYnZ(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapnXZY(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapnXZnY(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapnXnYZ(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapnXnYnZ(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapnXnZY(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapnXnZnY(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapnYXZ(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapnYXnZ(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapnYZX(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapnYZnX(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapnYnXZ(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapnYnXnZ(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapnYnZX(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapnYnZnX(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapnZXY(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapnZXnY(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapnZYX(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapnZYnX(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapnZnXY(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapnZnXnY(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapnZnYX(org.joml.Matrix3d arg0);
    org.joml.Matrix3d mapnZnYnX(org.joml.Matrix3d arg0);
    org.joml.Matrix3d negateX(org.joml.Matrix3d arg0);
    org.joml.Matrix3d negateY(org.joml.Matrix3d arg0);
    org.joml.Matrix3d negateZ(org.joml.Matrix3d arg0);
}
