package org.joml;

/** Auto-generated stub from paper-api-26.1.2.build.20-alpha.jar. See PLAN-FULL-STUBS.md. */
@SuppressWarnings({"unchecked", "rawtypes", "unused"})
public interface Matrix4fc {
    public static final int PLANE_NX = 0;
    public static final int PLANE_PX = 1;
    public static final int PLANE_NY = 2;
    public static final int PLANE_PY = 3;
    public static final int PLANE_NZ = 4;
    public static final int PLANE_PZ = 5;
    public static final int CORNER_NXNYNZ = 0;
    public static final int CORNER_PXNYNZ = 1;
    public static final int CORNER_PXPYNZ = 2;
    public static final int CORNER_NXPYNZ = 3;
    public static final int CORNER_PXNYPZ = 4;
    public static final int CORNER_NXNYPZ = 5;
    public static final int CORNER_NXPYPZ = 6;
    public static final int CORNER_PXPYPZ = 7;
    public static final byte PROPERTY_UNKNOWN = (byte) 0;
    public static final byte PROPERTY_PERSPECTIVE = (byte) 1;
    public static final byte PROPERTY_AFFINE = (byte) 2;
    public static final byte PROPERTY_IDENTITY = (byte) 4;
    public static final byte PROPERTY_TRANSLATION = (byte) 8;
    public static final byte PROPERTY_ORTHONORMAL = (byte) 16;
    int properties();
    float m00();
    float m01();
    float m02();
    float m03();
    float m10();
    float m11();
    float m12();
    float m13();
    float m20();
    float m21();
    float m22();
    float m23();
    float m30();
    float m31();
    float m32();
    float m33();
    org.joml.Matrix4f mul(org.joml.Matrix4fc arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f mul0(org.joml.Matrix4fc arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f mul(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, float arg6, float arg7, float arg8, float arg9, float arg10, float arg11, float arg12, float arg13, float arg14, float arg15, org.joml.Matrix4f arg16);
    org.joml.Matrix4f mul3x3(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, float arg6, float arg7, float arg8, org.joml.Matrix4f arg9);
    org.joml.Matrix4f mulLocal(org.joml.Matrix4fc arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f mulLocalAffine(org.joml.Matrix4fc arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f mul(org.joml.Matrix3x2fc arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f mul(org.joml.Matrix4x3fc arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f mulPerspectiveAffine(org.joml.Matrix4fc arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f mulPerspectiveAffine(org.joml.Matrix4x3fc arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f mulAffineR(org.joml.Matrix4fc arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f mulAffine(org.joml.Matrix4fc arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f mulTranslationAffine(org.joml.Matrix4fc arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f mulOrthoAffine(org.joml.Matrix4fc arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f fma4x3(org.joml.Matrix4fc arg0, float arg1, org.joml.Matrix4f arg2);
    org.joml.Matrix4f add(org.joml.Matrix4fc arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f sub(org.joml.Matrix4fc arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f mulComponentWise(org.joml.Matrix4fc arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f add4x3(org.joml.Matrix4fc arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f sub4x3(org.joml.Matrix4fc arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f mul4x3ComponentWise(org.joml.Matrix4fc arg0, org.joml.Matrix4f arg1);
    float determinant();
    float determinant3x3();
    float determinantAffine();
    org.joml.Matrix4f invert(org.joml.Matrix4f arg0);
    org.joml.Matrix4f invertPerspective(org.joml.Matrix4f arg0);
    org.joml.Matrix4f invertFrustum(org.joml.Matrix4f arg0);
    org.joml.Matrix4f invertOrtho(org.joml.Matrix4f arg0);
    org.joml.Matrix4f invertPerspectiveView(org.joml.Matrix4fc arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f invertPerspectiveView(org.joml.Matrix4x3fc arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f invertAffine(org.joml.Matrix4f arg0);
    org.joml.Matrix4f transpose(org.joml.Matrix4f arg0);
    org.joml.Matrix4f transpose3x3(org.joml.Matrix4f arg0);
    org.joml.Matrix3f transpose3x3(org.joml.Matrix3f arg0);
    org.joml.Vector3f getTranslation(org.joml.Vector3f arg0);
    org.joml.Vector3f getScale(org.joml.Vector3f arg0);
    org.joml.Matrix4f get(org.joml.Matrix4f arg0);
    org.joml.Matrix4x3f get4x3(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4d get(org.joml.Matrix4d arg0);
    org.joml.Matrix3f get3x3(org.joml.Matrix3f arg0);
    org.joml.Matrix3d get3x3(org.joml.Matrix3d arg0);
    org.joml.AxisAngle4f getRotation(org.joml.AxisAngle4f arg0);
    org.joml.AxisAngle4d getRotation(org.joml.AxisAngle4d arg0);
    org.joml.Quaternionf getUnnormalizedRotation(org.joml.Quaternionf arg0);
    org.joml.Quaternionf getNormalizedRotation(org.joml.Quaternionf arg0);
    org.joml.Quaterniond getUnnormalizedRotation(org.joml.Quaterniond arg0);
    org.joml.Quaterniond getNormalizedRotation(org.joml.Quaterniond arg0);
    java.nio.FloatBuffer get(java.nio.FloatBuffer arg0);
    java.nio.FloatBuffer get(int arg0, java.nio.FloatBuffer arg1);
    java.nio.ByteBuffer get(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer get(int arg0, java.nio.ByteBuffer arg1);
    java.nio.FloatBuffer get4x3(java.nio.FloatBuffer arg0);
    java.nio.FloatBuffer get4x3(int arg0, java.nio.FloatBuffer arg1);
    java.nio.ByteBuffer get4x3(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer get4x3(int arg0, java.nio.ByteBuffer arg1);
    java.nio.FloatBuffer get3x4(java.nio.FloatBuffer arg0);
    java.nio.FloatBuffer get3x4(int arg0, java.nio.FloatBuffer arg1);
    java.nio.ByteBuffer get3x4(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer get3x4(int arg0, java.nio.ByteBuffer arg1);
    java.nio.FloatBuffer getTransposed(java.nio.FloatBuffer arg0);
    java.nio.FloatBuffer getTransposed(int arg0, java.nio.FloatBuffer arg1);
    java.nio.ByteBuffer getTransposed(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer getTransposed(int arg0, java.nio.ByteBuffer arg1);
    java.nio.FloatBuffer get4x3Transposed(java.nio.FloatBuffer arg0);
    java.nio.FloatBuffer get4x3Transposed(int arg0, java.nio.FloatBuffer arg1);
    java.nio.ByteBuffer get4x3Transposed(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer get4x3Transposed(int arg0, java.nio.ByteBuffer arg1);
    org.joml.Matrix4fc getToAddress(long arg0);
    org.joml.Matrix4fc getTransposedToAddress(long arg0);
    float[] get(float[] arg0, int arg1);
    float[] get(float[] arg0);
    org.joml.Vector4f transform(org.joml.Vector4f arg0);
    org.joml.Vector4f transform(org.joml.Vector4fc arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f transform(float arg0, float arg1, float arg2, float arg3, org.joml.Vector4f arg4);
    org.joml.Vector4f transformTranspose(org.joml.Vector4f arg0);
    org.joml.Vector4f transformTranspose(org.joml.Vector4fc arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f transformTranspose(float arg0, float arg1, float arg2, float arg3, org.joml.Vector4f arg4);
    org.joml.Vector4f transformProject(org.joml.Vector4f arg0);
    org.joml.Vector4f transformProject(org.joml.Vector4fc arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f transformProject(float arg0, float arg1, float arg2, float arg3, org.joml.Vector4f arg4);
    org.joml.Vector3f transformProject(org.joml.Vector3f arg0);
    org.joml.Vector3f transformProject(org.joml.Vector3fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f transformProject(org.joml.Vector4fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f transformProject(float arg0, float arg1, float arg2, org.joml.Vector3f arg3);
    org.joml.Vector3f transformProject(float arg0, float arg1, float arg2, float arg3, org.joml.Vector3f arg4);
    org.joml.Vector3f transformPosition(org.joml.Vector3f arg0);
    org.joml.Vector3f transformPosition(org.joml.Vector3fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f transformPosition(float arg0, float arg1, float arg2, org.joml.Vector3f arg3);
    org.joml.Vector3f transformDirection(org.joml.Vector3f arg0);
    org.joml.Vector3f transformDirection(org.joml.Vector3fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f transformDirection(float arg0, float arg1, float arg2, org.joml.Vector3f arg3);
    org.joml.Vector4f transformAffine(org.joml.Vector4f arg0);
    org.joml.Vector4f transformAffine(org.joml.Vector4fc arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f transformAffine(float arg0, float arg1, float arg2, float arg3, org.joml.Vector4f arg4);
    org.joml.Matrix4f scale(org.joml.Vector3fc arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f scale(float arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f scaleXY(float arg0, float arg1, org.joml.Matrix4f arg2);
    org.joml.Matrix4f scale(float arg0, float arg1, float arg2, org.joml.Matrix4f arg3);
    org.joml.Matrix4f scaleAround(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, org.joml.Matrix4f arg6);
    org.joml.Matrix4f scaleAround(float arg0, float arg1, float arg2, float arg3, org.joml.Matrix4f arg4);
    org.joml.Matrix4f scaleLocal(float arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f scaleLocal(float arg0, float arg1, float arg2, org.joml.Matrix4f arg3);
    org.joml.Matrix4f scaleAroundLocal(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, org.joml.Matrix4f arg6);
    org.joml.Matrix4f scaleAroundLocal(float arg0, float arg1, float arg2, float arg3, org.joml.Matrix4f arg4);
    org.joml.Matrix4f rotateX(float arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f rotateY(float arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f rotateZ(float arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f rotateTowardsXY(float arg0, float arg1, org.joml.Matrix4f arg2);
    org.joml.Matrix4f rotateXYZ(float arg0, float arg1, float arg2, org.joml.Matrix4f arg3);
    org.joml.Matrix4f rotateAffineXYZ(float arg0, float arg1, float arg2, org.joml.Matrix4f arg3);
    org.joml.Matrix4f rotateZYX(float arg0, float arg1, float arg2, org.joml.Matrix4f arg3);
    org.joml.Matrix4f rotateAffineZYX(float arg0, float arg1, float arg2, org.joml.Matrix4f arg3);
    org.joml.Matrix4f rotateYXZ(float arg0, float arg1, float arg2, org.joml.Matrix4f arg3);
    org.joml.Matrix4f rotateAffineYXZ(float arg0, float arg1, float arg2, org.joml.Matrix4f arg3);
    org.joml.Matrix4f rotate(float arg0, float arg1, float arg2, float arg3, org.joml.Matrix4f arg4);
    org.joml.Matrix4f rotateTranslation(float arg0, float arg1, float arg2, float arg3, org.joml.Matrix4f arg4);
    org.joml.Matrix4f rotateAffine(float arg0, float arg1, float arg2, float arg3, org.joml.Matrix4f arg4);
    org.joml.Matrix4f rotateLocal(float arg0, float arg1, float arg2, float arg3, org.joml.Matrix4f arg4);
    org.joml.Matrix4f rotateLocalX(float arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f rotateLocalY(float arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f rotateLocalZ(float arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f translate(org.joml.Vector3fc arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f translate(float arg0, float arg1, float arg2, org.joml.Matrix4f arg3);
    org.joml.Matrix4f translateLocal(org.joml.Vector3fc arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f translateLocal(float arg0, float arg1, float arg2, org.joml.Matrix4f arg3);
    org.joml.Matrix4f ortho(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, boolean arg6, org.joml.Matrix4f arg7);
    org.joml.Matrix4f ortho(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, org.joml.Matrix4f arg6);
    org.joml.Matrix4f orthoLH(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, boolean arg6, org.joml.Matrix4f arg7);
    org.joml.Matrix4f orthoLH(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, org.joml.Matrix4f arg6);
    org.joml.Matrix4f orthoSymmetric(float arg0, float arg1, float arg2, float arg3, boolean arg4, org.joml.Matrix4f arg5);
    org.joml.Matrix4f orthoSymmetric(float arg0, float arg1, float arg2, float arg3, org.joml.Matrix4f arg4);
    org.joml.Matrix4f orthoSymmetricLH(float arg0, float arg1, float arg2, float arg3, boolean arg4, org.joml.Matrix4f arg5);
    org.joml.Matrix4f orthoSymmetricLH(float arg0, float arg1, float arg2, float arg3, org.joml.Matrix4f arg4);
    org.joml.Matrix4f ortho2D(float arg0, float arg1, float arg2, float arg3, org.joml.Matrix4f arg4);
    org.joml.Matrix4f ortho2DLH(float arg0, float arg1, float arg2, float arg3, org.joml.Matrix4f arg4);
    org.joml.Matrix4f lookAlong(org.joml.Vector3fc arg0, org.joml.Vector3fc arg1, org.joml.Matrix4f arg2);
    org.joml.Matrix4f lookAlong(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, org.joml.Matrix4f arg6);
    org.joml.Matrix4f lookAt(org.joml.Vector3fc arg0, org.joml.Vector3fc arg1, org.joml.Vector3fc arg2, org.joml.Matrix4f arg3);
    org.joml.Matrix4f lookAt(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, float arg6, float arg7, float arg8, org.joml.Matrix4f arg9);
    org.joml.Matrix4f lookAtPerspective(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, float arg6, float arg7, float arg8, org.joml.Matrix4f arg9);
    org.joml.Matrix4f lookAtLH(org.joml.Vector3fc arg0, org.joml.Vector3fc arg1, org.joml.Vector3fc arg2, org.joml.Matrix4f arg3);
    org.joml.Matrix4f lookAtLH(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, float arg6, float arg7, float arg8, org.joml.Matrix4f arg9);
    org.joml.Matrix4f lookAtPerspectiveLH(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, float arg6, float arg7, float arg8, org.joml.Matrix4f arg9);
    org.joml.Matrix4f tile(int arg0, int arg1, int arg2, int arg3, org.joml.Matrix4f arg4);
    org.joml.Matrix4f perspective(float arg0, float arg1, float arg2, float arg3, boolean arg4, org.joml.Matrix4f arg5);
    org.joml.Matrix4f perspective(float arg0, float arg1, float arg2, float arg3, org.joml.Matrix4f arg4);
    org.joml.Matrix4f perspectiveRect(float arg0, float arg1, float arg2, float arg3, boolean arg4, org.joml.Matrix4f arg5);
    org.joml.Matrix4f perspectiveRect(float arg0, float arg1, float arg2, float arg3, org.joml.Matrix4f arg4);
    org.joml.Matrix4f perspectiveOffCenter(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, boolean arg6, org.joml.Matrix4f arg7);
    org.joml.Matrix4f perspectiveOffCenter(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, org.joml.Matrix4f arg6);
    org.joml.Matrix4f perspectiveOffCenterFov(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, boolean arg6, org.joml.Matrix4f arg7);
    org.joml.Matrix4f perspectiveOffCenterFov(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, org.joml.Matrix4f arg6);
    org.joml.Matrix4f perspectiveOffCenterFovLH(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, boolean arg6, org.joml.Matrix4f arg7);
    org.joml.Matrix4f perspectiveOffCenterFovLH(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, org.joml.Matrix4f arg6);
    org.joml.Matrix4f perspectiveLH(float arg0, float arg1, float arg2, float arg3, boolean arg4, org.joml.Matrix4f arg5);
    org.joml.Matrix4f perspectiveLH(float arg0, float arg1, float arg2, float arg3, org.joml.Matrix4f arg4);
    org.joml.Matrix4f frustum(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, boolean arg6, org.joml.Matrix4f arg7);
    org.joml.Matrix4f frustum(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, org.joml.Matrix4f arg6);
    org.joml.Matrix4f frustumLH(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, boolean arg6, org.joml.Matrix4f arg7);
    org.joml.Matrix4f frustumLH(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, org.joml.Matrix4f arg6);
    org.joml.Matrix4f rotate(org.joml.Quaternionfc arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f rotateAffine(org.joml.Quaternionfc arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f rotateTranslation(org.joml.Quaternionfc arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f rotateAroundAffine(org.joml.Quaternionfc arg0, float arg1, float arg2, float arg3, org.joml.Matrix4f arg4);
    org.joml.Matrix4f rotateAround(org.joml.Quaternionfc arg0, float arg1, float arg2, float arg3, org.joml.Matrix4f arg4);
    org.joml.Matrix4f rotateLocal(org.joml.Quaternionfc arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f rotateAroundLocal(org.joml.Quaternionfc arg0, float arg1, float arg2, float arg3, org.joml.Matrix4f arg4);
    org.joml.Matrix4f rotate(org.joml.AxisAngle4f arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f rotate(float arg0, org.joml.Vector3fc arg1, org.joml.Matrix4f arg2);
    org.joml.Vector4f unproject(float arg0, float arg1, float arg2, int[] arg3, org.joml.Vector4f arg4);
    org.joml.Vector3f unproject(float arg0, float arg1, float arg2, int[] arg3, org.joml.Vector3f arg4);
    org.joml.Vector4f unproject(org.joml.Vector3fc arg0, int[] arg1, org.joml.Vector4f arg2);
    org.joml.Vector3f unproject(org.joml.Vector3fc arg0, int[] arg1, org.joml.Vector3f arg2);
    org.joml.Matrix4f unprojectRay(float arg0, float arg1, int[] arg2, org.joml.Vector3f arg3, org.joml.Vector3f arg4);
    org.joml.Matrix4f unprojectRay(org.joml.Vector2fc arg0, int[] arg1, org.joml.Vector3f arg2, org.joml.Vector3f arg3);
    org.joml.Vector4f unprojectInv(org.joml.Vector3fc arg0, int[] arg1, org.joml.Vector4f arg2);
    org.joml.Vector4f unprojectInv(float arg0, float arg1, float arg2, int[] arg3, org.joml.Vector4f arg4);
    org.joml.Matrix4f unprojectInvRay(org.joml.Vector2fc arg0, int[] arg1, org.joml.Vector3f arg2, org.joml.Vector3f arg3);
    org.joml.Matrix4f unprojectInvRay(float arg0, float arg1, int[] arg2, org.joml.Vector3f arg3, org.joml.Vector3f arg4);
    org.joml.Vector3f unprojectInv(org.joml.Vector3fc arg0, int[] arg1, org.joml.Vector3f arg2);
    org.joml.Vector3f unprojectInv(float arg0, float arg1, float arg2, int[] arg3, org.joml.Vector3f arg4);
    org.joml.Vector4f project(float arg0, float arg1, float arg2, int[] arg3, org.joml.Vector4f arg4);
    org.joml.Vector3f project(float arg0, float arg1, float arg2, int[] arg3, org.joml.Vector3f arg4);
    org.joml.Vector4f project(org.joml.Vector3fc arg0, int[] arg1, org.joml.Vector4f arg2);
    org.joml.Vector3f project(org.joml.Vector3fc arg0, int[] arg1, org.joml.Vector3f arg2);
    org.joml.Matrix4f reflect(float arg0, float arg1, float arg2, float arg3, org.joml.Matrix4f arg4);
    org.joml.Matrix4f reflect(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, org.joml.Matrix4f arg6);
    org.joml.Matrix4f reflect(org.joml.Quaternionfc arg0, org.joml.Vector3fc arg1, org.joml.Matrix4f arg2);
    org.joml.Matrix4f reflect(org.joml.Vector3fc arg0, org.joml.Vector3fc arg1, org.joml.Matrix4f arg2);
    org.joml.Vector4f getRow(int arg0, org.joml.Vector4f arg1) throws java.lang.IndexOutOfBoundsException;
    org.joml.Vector3f getRow(int arg0, org.joml.Vector3f arg1) throws java.lang.IndexOutOfBoundsException;
    org.joml.Vector4f getColumn(int arg0, org.joml.Vector4f arg1) throws java.lang.IndexOutOfBoundsException;
    org.joml.Vector3f getColumn(int arg0, org.joml.Vector3f arg1) throws java.lang.IndexOutOfBoundsException;
    float get(int arg0, int arg1);
    float getRowColumn(int arg0, int arg1);
    org.joml.Matrix4f normal(org.joml.Matrix4f arg0);
    org.joml.Matrix3f normal(org.joml.Matrix3f arg0);
    org.joml.Matrix3f cofactor3x3(org.joml.Matrix3f arg0);
    org.joml.Matrix4f cofactor3x3(org.joml.Matrix4f arg0);
    org.joml.Matrix4f normalize3x3(org.joml.Matrix4f arg0);
    org.joml.Matrix3f normalize3x3(org.joml.Matrix3f arg0);
    org.joml.Vector4f frustumPlane(int arg0, org.joml.Vector4f arg1);
    org.joml.Vector3f frustumCorner(int arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f perspectiveOrigin(org.joml.Vector3f arg0);
    org.joml.Vector3f perspectiveInvOrigin(org.joml.Vector3f arg0);
    float perspectiveFov();
    float perspectiveNear();
    float perspectiveFar();
    org.joml.Vector3f frustumRayDir(float arg0, float arg1, org.joml.Vector3f arg2);
    org.joml.Vector3f positiveZ(org.joml.Vector3f arg0);
    org.joml.Vector3f normalizedPositiveZ(org.joml.Vector3f arg0);
    org.joml.Vector3f positiveX(org.joml.Vector3f arg0);
    org.joml.Vector3f normalizedPositiveX(org.joml.Vector3f arg0);
    org.joml.Vector3f positiveY(org.joml.Vector3f arg0);
    org.joml.Vector3f normalizedPositiveY(org.joml.Vector3f arg0);
    org.joml.Vector3f originAffine(org.joml.Vector3f arg0);
    org.joml.Vector3f origin(org.joml.Vector3f arg0);
    org.joml.Matrix4f shadow(org.joml.Vector4f arg0, float arg1, float arg2, float arg3, float arg4, org.joml.Matrix4f arg5);
    org.joml.Matrix4f shadow(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, float arg6, float arg7, org.joml.Matrix4f arg8);
    org.joml.Matrix4f shadow(org.joml.Vector4f arg0, org.joml.Matrix4fc arg1, org.joml.Matrix4f arg2);
    org.joml.Matrix4f shadow(float arg0, float arg1, float arg2, float arg3, org.joml.Matrix4fc arg4, org.joml.Matrix4f arg5);
    org.joml.Matrix4f pick(float arg0, float arg1, float arg2, float arg3, int[] arg4, org.joml.Matrix4f arg5);
    boolean isAffine();
    org.joml.Matrix4f arcball(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, org.joml.Matrix4f arg6);
    org.joml.Matrix4f arcball(float arg0, org.joml.Vector3fc arg1, float arg2, float arg3, org.joml.Matrix4f arg4);
    org.joml.Matrix4f frustumAabb(org.joml.Vector3f arg0, org.joml.Vector3f arg1);
    org.joml.Matrix4f projectedGridRange(org.joml.Matrix4fc arg0, float arg1, float arg2, org.joml.Matrix4f arg3);
    org.joml.Matrix4f perspectiveFrustumSlice(float arg0, float arg1, org.joml.Matrix4f arg2);
    org.joml.Matrix4f orthoCrop(org.joml.Matrix4fc arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f transformAab(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, org.joml.Vector3f arg6, org.joml.Vector3f arg7);
    org.joml.Matrix4f transformAab(org.joml.Vector3fc arg0, org.joml.Vector3fc arg1, org.joml.Vector3f arg2, org.joml.Vector3f arg3);
    org.joml.Matrix4f lerp(org.joml.Matrix4fc arg0, float arg1, org.joml.Matrix4f arg2);
    org.joml.Matrix4f rotateTowards(org.joml.Vector3fc arg0, org.joml.Vector3fc arg1, org.joml.Matrix4f arg2);
    org.joml.Matrix4f rotateTowards(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, org.joml.Matrix4f arg6);
    org.joml.Vector3f getEulerAnglesXYZ(org.joml.Vector3f arg0);
    org.joml.Vector3f getEulerAnglesZYX(org.joml.Vector3f arg0);
    org.joml.Vector3f getEulerAnglesYXZ(org.joml.Vector3f arg0);
    boolean testPoint(float arg0, float arg1, float arg2);
    boolean testSphere(float arg0, float arg1, float arg2, float arg3);
    boolean testAab(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5);
    org.joml.Matrix4f obliqueZ(float arg0, float arg1, org.joml.Matrix4f arg2);
    org.joml.Matrix4f withLookAtUp(org.joml.Vector3fc arg0, org.joml.Matrix4f arg1);
    org.joml.Matrix4f withLookAtUp(float arg0, float arg1, float arg2, org.joml.Matrix4f arg3);
    org.joml.Matrix4f mapXZY(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapXZnY(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapXnYnZ(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapXnZY(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapXnZnY(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapYXZ(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapYXnZ(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapYZX(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapYZnX(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapYnXZ(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapYnXnZ(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapYnZX(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapYnZnX(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapZXY(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapZXnY(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapZYX(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapZYnX(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapZnXY(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapZnXnY(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapZnYX(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapZnYnX(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapnXYnZ(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapnXZY(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapnXZnY(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapnXnYZ(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapnXnYnZ(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapnXnZY(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapnXnZnY(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapnYXZ(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapnYXnZ(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapnYZX(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapnYZnX(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapnYnXZ(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapnYnXnZ(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapnYnZX(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapnYnZnX(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapnZXY(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapnZXnY(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapnZYX(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapnZYnX(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapnZnXY(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapnZnXnY(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapnZnYX(org.joml.Matrix4f arg0);
    org.joml.Matrix4f mapnZnYnX(org.joml.Matrix4f arg0);
    org.joml.Matrix4f negateX(org.joml.Matrix4f arg0);
    org.joml.Matrix4f negateY(org.joml.Matrix4f arg0);
    org.joml.Matrix4f negateZ(org.joml.Matrix4f arg0);
    boolean equals(org.joml.Matrix4fc arg0, float arg1);
    boolean isFinite();
}
