package org.joml;

/** Auto-generated stub from paper-api-26.1.2.build.20-alpha.jar. See PLAN-FULL-STUBS.md. */
@SuppressWarnings({"unchecked", "rawtypes", "unused"})
abstract class MemUtil {
    public static final org.joml.MemUtil INSTANCE = null;
    protected MemUtil() {}
    public abstract void put(org.joml.Matrix4f arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void put(org.joml.Matrix4f arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void put(org.joml.Matrix4x3f arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void put(org.joml.Matrix4x3f arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void put4x4(org.joml.Matrix4x3f arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void put4x4(org.joml.Matrix4x3f arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void put4x4(org.joml.Matrix4x3d arg0, int arg1, java.nio.DoubleBuffer arg2);
    public abstract void put4x4(org.joml.Matrix4x3d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void put4x4(org.joml.Matrix3x2f arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void put4x4(org.joml.Matrix3x2f arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void put4x4(org.joml.Matrix3x2d arg0, int arg1, java.nio.DoubleBuffer arg2);
    public abstract void put4x4(org.joml.Matrix3x2d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void put3x3(org.joml.Matrix3x2f arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void put3x3(org.joml.Matrix3x2f arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void put3x3(org.joml.Matrix3x2d arg0, int arg1, java.nio.DoubleBuffer arg2);
    public abstract void put3x3(org.joml.Matrix3x2d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void put4x3(org.joml.Matrix4f arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void put4x3(org.joml.Matrix4f arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void put3x4(org.joml.Matrix4f arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void put3x4(org.joml.Matrix4f arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void put3x4(org.joml.Matrix4x3f arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void put3x4(org.joml.Matrix4x3f arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void put3x4(org.joml.Matrix3f arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void put3x4(org.joml.Matrix3f arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void putTransposed(org.joml.Matrix4f arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void putTransposed(org.joml.Matrix4f arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void put4x3Transposed(org.joml.Matrix4f arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void put4x3Transposed(org.joml.Matrix4f arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void putTransposed(org.joml.Matrix4x3f arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void putTransposed(org.joml.Matrix4x3f arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void putTransposed(org.joml.Matrix3x2f arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void putTransposed(org.joml.Matrix3f arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void putTransposed(org.joml.Matrix3f arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void putTransposed(org.joml.Matrix2f arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void putTransposed(org.joml.Matrix2f arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void put(org.joml.Matrix4d arg0, int arg1, java.nio.DoubleBuffer arg2);
    public abstract void put(org.joml.Matrix4d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void put(org.joml.Matrix4x3d arg0, int arg1, java.nio.DoubleBuffer arg2);
    public abstract void put(org.joml.Matrix4x3d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void putf(org.joml.Matrix4d arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void putf(org.joml.Matrix4d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void putf(org.joml.Matrix4x3d arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void putf(org.joml.Matrix4x3d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void put4x3Transposed(org.joml.Matrix4d arg0, int arg1, java.nio.DoubleBuffer arg2);
    public abstract void put4x3Transposed(org.joml.Matrix4d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void putTransposed(org.joml.Matrix4d arg0, int arg1, java.nio.DoubleBuffer arg2);
    public abstract void putTransposed(org.joml.Matrix4d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void putTransposed(org.joml.Matrix4x3d arg0, int arg1, java.nio.DoubleBuffer arg2);
    public abstract void putTransposed(org.joml.Matrix4x3d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void putTransposed(org.joml.Matrix3d arg0, int arg1, java.nio.DoubleBuffer arg2);
    public abstract void putTransposed(org.joml.Matrix3d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void putTransposed(org.joml.Matrix3x2d arg0, int arg1, java.nio.DoubleBuffer arg2);
    public abstract void putTransposed(org.joml.Matrix3x2d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void putTransposed(org.joml.Matrix2d arg0, int arg1, java.nio.DoubleBuffer arg2);
    public abstract void putTransposed(org.joml.Matrix2d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void putfTransposed(org.joml.Matrix4d arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void putfTransposed(org.joml.Matrix4d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void putfTransposed(org.joml.Matrix4x3d arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void putfTransposed(org.joml.Matrix4x3d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void putfTransposed(org.joml.Matrix3d arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void putfTransposed(org.joml.Matrix3d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void putfTransposed(org.joml.Matrix3x2d arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void putfTransposed(org.joml.Matrix3x2d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void putfTransposed(org.joml.Matrix2d arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void putfTransposed(org.joml.Matrix2d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void put(org.joml.Matrix3f arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void put(org.joml.Matrix3f arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void put(org.joml.Matrix3d arg0, int arg1, java.nio.DoubleBuffer arg2);
    public abstract void put(org.joml.Matrix3d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void putf(org.joml.Matrix3d arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void putf(org.joml.Matrix3d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void put(org.joml.Matrix3x2f arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void put(org.joml.Matrix3x2f arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void put(org.joml.Matrix3x2d arg0, int arg1, java.nio.DoubleBuffer arg2);
    public abstract void put(org.joml.Matrix3x2d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void put(org.joml.Matrix2f arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void put(org.joml.Matrix2f arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void put(org.joml.Matrix2d arg0, int arg1, java.nio.DoubleBuffer arg2);
    public abstract void put(org.joml.Matrix2d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void putf(org.joml.Matrix2d arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void putf(org.joml.Matrix2d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void put(org.joml.Vector4d arg0, int arg1, java.nio.DoubleBuffer arg2);
    public abstract void put(org.joml.Vector4d arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void put(org.joml.Vector4d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void putf(org.joml.Vector4d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void put(org.joml.Vector4f arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void put(org.joml.Vector4f arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void put(org.joml.Vector4i arg0, int arg1, java.nio.IntBuffer arg2);
    public abstract void put(org.joml.Vector4i arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void put(org.joml.Vector4L arg0, int arg1, java.nio.LongBuffer arg2);
    public abstract void put(org.joml.Vector4L arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void put(org.joml.Vector3f arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void put(org.joml.Vector3f arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void put(org.joml.Vector3d arg0, int arg1, java.nio.DoubleBuffer arg2);
    public abstract void put(org.joml.Vector3d arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void put(org.joml.Vector3d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void putf(org.joml.Vector3d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void put(org.joml.Vector3i arg0, int arg1, java.nio.IntBuffer arg2);
    public abstract void put(org.joml.Vector3i arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void put(org.joml.Vector3L arg0, int arg1, java.nio.LongBuffer arg2);
    public abstract void put(org.joml.Vector3L arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void put(org.joml.Vector2f arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void put(org.joml.Vector2f arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void put(org.joml.Vector2d arg0, int arg1, java.nio.DoubleBuffer arg2);
    public abstract void put(org.joml.Vector2d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void put(org.joml.Vector2i arg0, int arg1, java.nio.IntBuffer arg2);
    public abstract void put(org.joml.Vector2i arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void put(org.joml.Vector2L arg0, int arg1, java.nio.LongBuffer arg2);
    public abstract void put(org.joml.Vector2L arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void get(org.joml.Matrix4f arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void get(org.joml.Matrix4f arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void getTransposed(org.joml.Matrix4f arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void getTransposed(org.joml.Matrix4f arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void get(org.joml.Matrix4x3f arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void get(org.joml.Matrix4x3f arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void get(org.joml.Matrix4d arg0, int arg1, java.nio.DoubleBuffer arg2);
    public abstract void get(org.joml.Matrix4d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void get(org.joml.Matrix4x3d arg0, int arg1, java.nio.DoubleBuffer arg2);
    public abstract void get(org.joml.Matrix4x3d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void getf(org.joml.Matrix4d arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void getf(org.joml.Matrix4d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void getf(org.joml.Matrix4x3d arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void getf(org.joml.Matrix4x3d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void get(org.joml.Matrix3f arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void get(org.joml.Matrix3f arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void get(org.joml.Matrix3d arg0, int arg1, java.nio.DoubleBuffer arg2);
    public abstract void get(org.joml.Matrix3d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void get(org.joml.Matrix3x2f arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void get(org.joml.Matrix3x2f arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void get(org.joml.Matrix3x2d arg0, int arg1, java.nio.DoubleBuffer arg2);
    public abstract void get(org.joml.Matrix3x2d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void getf(org.joml.Matrix3d arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void getf(org.joml.Matrix3d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void get(org.joml.Matrix2f arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void get(org.joml.Matrix2f arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void get(org.joml.Matrix2d arg0, int arg1, java.nio.DoubleBuffer arg2);
    public abstract void get(org.joml.Matrix2d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void getf(org.joml.Matrix2d arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void getf(org.joml.Matrix2d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void get(org.joml.Vector4d arg0, int arg1, java.nio.DoubleBuffer arg2);
    public abstract void get(org.joml.Vector4d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void get(org.joml.Vector4f arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void get(org.joml.Vector4f arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void get(org.joml.Vector4i arg0, int arg1, java.nio.IntBuffer arg2);
    public abstract void get(org.joml.Vector4i arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void get(org.joml.Vector4L arg0, int arg1, java.nio.LongBuffer arg2);
    public abstract void get(org.joml.Vector4L arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void get(org.joml.Vector3f arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void get(org.joml.Vector3f arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void get(org.joml.Vector3d arg0, int arg1, java.nio.DoubleBuffer arg2);
    public abstract void get(org.joml.Vector3d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void get(org.joml.Vector3i arg0, int arg1, java.nio.IntBuffer arg2);
    public abstract void get(org.joml.Vector3i arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void get(org.joml.Vector3L arg0, int arg1, java.nio.LongBuffer arg2);
    public abstract void get(org.joml.Vector3L arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void get(org.joml.Vector2f arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void get(org.joml.Vector2f arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void get(org.joml.Vector2d arg0, int arg1, java.nio.DoubleBuffer arg2);
    public abstract void get(org.joml.Vector2d arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void get(org.joml.Vector2i arg0, int arg1, java.nio.IntBuffer arg2);
    public abstract void get(org.joml.Vector2i arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void get(org.joml.Vector2L arg0, int arg1, java.nio.LongBuffer arg2);
    public abstract void get(org.joml.Vector2L arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void putMatrix3f(org.joml.Quaternionf arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void putMatrix3f(org.joml.Quaternionf arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void putMatrix4f(org.joml.Quaternionf arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void putMatrix4f(org.joml.Quaternionf arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract void putMatrix4x3f(org.joml.Quaternionf arg0, int arg1, java.nio.ByteBuffer arg2);
    public abstract void putMatrix4x3f(org.joml.Quaternionf arg0, int arg1, java.nio.FloatBuffer arg2);
    public abstract float get(org.joml.Matrix4f arg0, int arg1, int arg2);
    public abstract org.joml.Matrix4f set(org.joml.Matrix4f arg0, int arg1, int arg2, float arg3);
    public abstract double get(org.joml.Matrix4d arg0, int arg1, int arg2);
    public abstract org.joml.Matrix4d set(org.joml.Matrix4d arg0, int arg1, int arg2, double arg3);
    public abstract float get(org.joml.Matrix3f arg0, int arg1, int arg2);
    public abstract org.joml.Matrix3f set(org.joml.Matrix3f arg0, int arg1, int arg2, float arg3);
    public abstract double get(org.joml.Matrix3d arg0, int arg1, int arg2);
    public abstract org.joml.Matrix3d set(org.joml.Matrix3d arg0, int arg1, int arg2, double arg3);
    public abstract org.joml.Vector4f getColumn(org.joml.Matrix4f arg0, int arg1, org.joml.Vector4f arg2);
    public abstract org.joml.Matrix4f setColumn(org.joml.Vector4f arg0, int arg1, org.joml.Matrix4f arg2);
    public abstract org.joml.Matrix4f setColumn(org.joml.Vector4fc arg0, int arg1, org.joml.Matrix4f arg2);
    public abstract void copy(org.joml.Matrix4fc arg0, org.joml.Matrix4f arg1);
    public abstract void copy(org.joml.Matrix4x3fc arg0, org.joml.Matrix4x3f arg1);
    public abstract void copy(org.joml.Matrix4fc arg0, org.joml.Matrix4x3f arg1);
    public abstract void copy(org.joml.Matrix4x3fc arg0, org.joml.Matrix4f arg1);
    public abstract void copy(org.joml.Matrix3fc arg0, org.joml.Matrix3f arg1);
    public abstract void copy(org.joml.Matrix3fc arg0, org.joml.Matrix4f arg1);
    public abstract void copy(org.joml.Matrix4fc arg0, org.joml.Matrix3f arg1);
    public abstract void copy(org.joml.Matrix3fc arg0, org.joml.Matrix4x3f arg1);
    public abstract void copy(org.joml.Matrix3x2fc arg0, org.joml.Matrix3x2f arg1);
    public abstract void copy(org.joml.Matrix3x2dc arg0, org.joml.Matrix3x2d arg1);
    public abstract void copy(org.joml.Matrix2fc arg0, org.joml.Matrix2f arg1);
    public abstract void copy(org.joml.Matrix2dc arg0, org.joml.Matrix2d arg1);
    public abstract void copy(org.joml.Matrix2fc arg0, org.joml.Matrix3f arg1);
    public abstract void copy(org.joml.Matrix3fc arg0, org.joml.Matrix2f arg1);
    public abstract void copy(org.joml.Matrix2fc arg0, org.joml.Matrix3x2f arg1);
    public abstract void copy(org.joml.Matrix3x2fc arg0, org.joml.Matrix2f arg1);
    public abstract void copy(org.joml.Matrix2dc arg0, org.joml.Matrix3d arg1);
    public abstract void copy(org.joml.Matrix3dc arg0, org.joml.Matrix2d arg1);
    public abstract void copy(org.joml.Matrix2dc arg0, org.joml.Matrix3x2d arg1);
    public abstract void copy(org.joml.Matrix3x2dc arg0, org.joml.Matrix2d arg1);
    public abstract void copy3x3(org.joml.Matrix4fc arg0, org.joml.Matrix4f arg1);
    public abstract void copy3x3(org.joml.Matrix4x3fc arg0, org.joml.Matrix4x3f arg1);
    public abstract void copy3x3(org.joml.Matrix3fc arg0, org.joml.Matrix4x3f arg1);
    public abstract void copy3x3(org.joml.Matrix3fc arg0, org.joml.Matrix4f arg1);
    public abstract void copy4x3(org.joml.Matrix4fc arg0, org.joml.Matrix4f arg1);
    public abstract void copy4x3(org.joml.Matrix4x3fc arg0, org.joml.Matrix4f arg1);
    public abstract void copy(float[] arg0, int arg1, org.joml.Matrix4f arg2);
    public abstract void copyTransposed(float[] arg0, int arg1, org.joml.Matrix4f arg2);
    public abstract void copy(float[] arg0, int arg1, org.joml.Matrix3f arg2);
    public abstract void copy(float[] arg0, int arg1, org.joml.Matrix4x3f arg2);
    public abstract void copy(float[] arg0, int arg1, org.joml.Matrix3x2f arg2);
    public abstract void copy(double[] arg0, int arg1, org.joml.Matrix3x2d arg2);
    public abstract void copy(float[] arg0, int arg1, org.joml.Matrix3x2d arg2);
    public abstract void copy(float[] arg0, int arg1, org.joml.Matrix2f arg2);
    public abstract void copy(double[] arg0, int arg1, org.joml.Matrix2d arg2);
    public abstract void copy(org.joml.Matrix4fc arg0, float[] arg1, int arg2);
    public abstract void copy(org.joml.Matrix3fc arg0, float[] arg1, int arg2);
    public abstract void copy(org.joml.Matrix4x3fc arg0, float[] arg1, int arg2);
    public abstract void copy(org.joml.Matrix3x2fc arg0, float[] arg1, int arg2);
    public abstract void copy(org.joml.Matrix3x2dc arg0, double[] arg1, int arg2);
    public abstract void copy(org.joml.Matrix2fc arg0, float[] arg1, int arg2);
    public abstract void copy(org.joml.Matrix2dc arg0, double[] arg1, int arg2);
    public abstract void copy4x4(org.joml.Matrix4x3fc arg0, float[] arg1, int arg2);
    public abstract void copy4x4(org.joml.Matrix4x3dc arg0, float[] arg1, int arg2);
    public abstract void copy4x4(org.joml.Matrix4x3dc arg0, double[] arg1, int arg2);
    public abstract void copy4x4(org.joml.Matrix3x2fc arg0, float[] arg1, int arg2);
    public abstract void copy4x4(org.joml.Matrix3x2dc arg0, double[] arg1, int arg2);
    public abstract void copy3x3(org.joml.Matrix3x2fc arg0, float[] arg1, int arg2);
    public abstract void copy3x3(org.joml.Matrix3x2dc arg0, double[] arg1, int arg2);
    public abstract void identity(org.joml.Matrix4f arg0);
    public abstract void identity(org.joml.Matrix4x3f arg0);
    public abstract void identity(org.joml.Matrix3f arg0);
    public abstract void identity(org.joml.Matrix3x2f arg0);
    public abstract void identity(org.joml.Matrix3x2d arg0);
    public abstract void identity(org.joml.Matrix2f arg0);
    public abstract void swap(org.joml.Matrix4f arg0, org.joml.Matrix4f arg1);
    public abstract void swap(org.joml.Matrix4x3f arg0, org.joml.Matrix4x3f arg1);
    public abstract void swap(org.joml.Matrix3f arg0, org.joml.Matrix3f arg1);
    public abstract void swap(org.joml.Matrix2f arg0, org.joml.Matrix2f arg1);
    public abstract void swap(org.joml.Matrix2d arg0, org.joml.Matrix2d arg1);
    public abstract void zero(org.joml.Matrix4f arg0);
    public abstract void zero(org.joml.Matrix4x3f arg0);
    public abstract void zero(org.joml.Matrix3f arg0);
    public abstract void zero(org.joml.Matrix3x2f arg0);
    public abstract void zero(org.joml.Matrix3x2d arg0);
    public abstract void zero(org.joml.Matrix2f arg0);
    public abstract void zero(org.joml.Matrix2d arg0);
}
