package org.joml;

/** Auto-generated stub from paper-api-26.1.2.build.20-alpha.jar. See PLAN-FULL-STUBS.md. */
@SuppressWarnings({"unchecked", "rawtypes", "unused"})
public interface Quaterniondc {
    double x();
    double y();
    double z();
    double w();
    org.joml.Quaterniond normalize(org.joml.Quaterniond arg0);
    org.joml.Quaterniond add(double arg0, double arg1, double arg2, double arg3, org.joml.Quaterniond arg4);
    org.joml.Quaterniond add(org.joml.Quaterniondc arg0, org.joml.Quaterniond arg1);
    org.joml.Quaterniond sub(double arg0, double arg1, double arg2, double arg3, org.joml.Quaterniond arg4);
    org.joml.Quaterniond sub(org.joml.Quaterniondc arg0, org.joml.Quaterniond arg1);
    double dot(org.joml.Quaterniondc arg0);
    double angle();
    org.joml.Matrix3d get(org.joml.Matrix3d arg0);
    org.joml.Matrix3f get(org.joml.Matrix3f arg0);
    org.joml.Matrix4d get(org.joml.Matrix4d arg0);
    org.joml.Matrix4f get(org.joml.Matrix4f arg0);
    org.joml.AxisAngle4f get(org.joml.AxisAngle4f arg0);
    org.joml.AxisAngle4d get(org.joml.AxisAngle4d arg0);
    org.joml.Quaterniond get(org.joml.Quaterniond arg0);
    org.joml.Quaternionf get(org.joml.Quaternionf arg0);
    org.joml.Quaterniond mul(org.joml.Quaterniondc arg0, org.joml.Quaterniond arg1);
    org.joml.Quaterniond mul(double arg0, double arg1, double arg2, double arg3, org.joml.Quaterniond arg4);
    org.joml.Quaterniond mul(double arg0, org.joml.Quaterniond arg1);
    org.joml.Quaterniond premul(org.joml.Quaterniondc arg0, org.joml.Quaterniond arg1);
    org.joml.Quaterniond premul(double arg0, double arg1, double arg2, double arg3, org.joml.Quaterniond arg4);
    org.joml.Vector3d transform(org.joml.Vector3d arg0);
    org.joml.Vector3d transformInverse(org.joml.Vector3d arg0);
    org.joml.Vector3d transformUnit(org.joml.Vector3d arg0);
    org.joml.Vector3d transformInverseUnit(org.joml.Vector3d arg0);
    org.joml.Vector3d transformPositiveX(org.joml.Vector3d arg0);
    org.joml.Vector4d transformPositiveX(org.joml.Vector4d arg0);
    org.joml.Vector3d transformUnitPositiveX(org.joml.Vector3d arg0);
    org.joml.Vector4d transformUnitPositiveX(org.joml.Vector4d arg0);
    org.joml.Vector3d transformPositiveY(org.joml.Vector3d arg0);
    org.joml.Vector4d transformPositiveY(org.joml.Vector4d arg0);
    org.joml.Vector3d transformUnitPositiveY(org.joml.Vector3d arg0);
    org.joml.Vector4d transformUnitPositiveY(org.joml.Vector4d arg0);
    org.joml.Vector3d transformPositiveZ(org.joml.Vector3d arg0);
    org.joml.Vector4d transformPositiveZ(org.joml.Vector4d arg0);
    org.joml.Vector3d transformUnitPositiveZ(org.joml.Vector3d arg0);
    org.joml.Vector4d transformUnitPositiveZ(org.joml.Vector4d arg0);
    org.joml.Vector4d transform(org.joml.Vector4d arg0);
    org.joml.Vector4d transformInverse(org.joml.Vector4d arg0);
    org.joml.Vector3d transform(org.joml.Vector3dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d transformInverse(org.joml.Vector3dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d transform(double arg0, double arg1, double arg2, org.joml.Vector3d arg3);
    org.joml.Vector3d transformInverse(double arg0, double arg1, double arg2, org.joml.Vector3d arg3);
    org.joml.Vector4d transform(org.joml.Vector4dc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d transformInverse(org.joml.Vector4dc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d transform(double arg0, double arg1, double arg2, org.joml.Vector4d arg3);
    org.joml.Vector4d transformInverse(double arg0, double arg1, double arg2, org.joml.Vector4d arg3);
    org.joml.Vector3f transform(org.joml.Vector3f arg0);
    org.joml.Vector3f transformInverse(org.joml.Vector3f arg0);
    org.joml.Vector4d transformUnit(org.joml.Vector4d arg0);
    org.joml.Vector4d transformInverseUnit(org.joml.Vector4d arg0);
    org.joml.Vector3d transformUnit(org.joml.Vector3dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d transformInverseUnit(org.joml.Vector3dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d transformUnit(double arg0, double arg1, double arg2, org.joml.Vector3d arg3);
    org.joml.Vector3d transformInverseUnit(double arg0, double arg1, double arg2, org.joml.Vector3d arg3);
    org.joml.Vector4d transformUnit(org.joml.Vector4dc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d transformInverseUnit(org.joml.Vector4dc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d transformUnit(double arg0, double arg1, double arg2, org.joml.Vector4d arg3);
    org.joml.Vector4d transformInverseUnit(double arg0, double arg1, double arg2, org.joml.Vector4d arg3);
    org.joml.Vector3f transformUnit(org.joml.Vector3f arg0);
    org.joml.Vector3f transformInverseUnit(org.joml.Vector3f arg0);
    org.joml.Vector3f transformPositiveX(org.joml.Vector3f arg0);
    org.joml.Vector4f transformPositiveX(org.joml.Vector4f arg0);
    org.joml.Vector3f transformUnitPositiveX(org.joml.Vector3f arg0);
    org.joml.Vector4f transformUnitPositiveX(org.joml.Vector4f arg0);
    org.joml.Vector3f transformPositiveY(org.joml.Vector3f arg0);
    org.joml.Vector4f transformPositiveY(org.joml.Vector4f arg0);
    org.joml.Vector3f transformUnitPositiveY(org.joml.Vector3f arg0);
    org.joml.Vector4f transformUnitPositiveY(org.joml.Vector4f arg0);
    org.joml.Vector3f transformPositiveZ(org.joml.Vector3f arg0);
    org.joml.Vector4f transformPositiveZ(org.joml.Vector4f arg0);
    org.joml.Vector3f transformUnitPositiveZ(org.joml.Vector3f arg0);
    org.joml.Vector4f transformUnitPositiveZ(org.joml.Vector4f arg0);
    org.joml.Vector4f transform(org.joml.Vector4f arg0);
    org.joml.Vector4f transformInverse(org.joml.Vector4f arg0);
    org.joml.Vector3f transform(org.joml.Vector3fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f transformInverse(org.joml.Vector3fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f transform(double arg0, double arg1, double arg2, org.joml.Vector3f arg3);
    org.joml.Vector3f transformInverse(double arg0, double arg1, double arg2, org.joml.Vector3f arg3);
    org.joml.Vector4f transform(org.joml.Vector4fc arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f transformInverse(org.joml.Vector4fc arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f transform(double arg0, double arg1, double arg2, org.joml.Vector4f arg3);
    org.joml.Vector4f transformInverse(double arg0, double arg1, double arg2, org.joml.Vector4f arg3);
    org.joml.Vector4f transformUnit(org.joml.Vector4f arg0);
    org.joml.Vector4f transformInverseUnit(org.joml.Vector4f arg0);
    org.joml.Vector3f transformUnit(org.joml.Vector3fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f transformInverseUnit(org.joml.Vector3fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f transformUnit(double arg0, double arg1, double arg2, org.joml.Vector3f arg3);
    org.joml.Vector3f transformInverseUnit(double arg0, double arg1, double arg2, org.joml.Vector3f arg3);
    org.joml.Vector4f transformUnit(org.joml.Vector4fc arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f transformInverseUnit(org.joml.Vector4fc arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f transformUnit(double arg0, double arg1, double arg2, org.joml.Vector4f arg3);
    org.joml.Vector4f transformInverseUnit(double arg0, double arg1, double arg2, org.joml.Vector4f arg3);
    org.joml.Quaterniond invert(org.joml.Quaterniond arg0);
    org.joml.Quaterniond div(org.joml.Quaterniondc arg0, org.joml.Quaterniond arg1);
    org.joml.Quaterniond div(double arg0, org.joml.Quaterniond arg1);
    org.joml.Quaterniond conjugate(org.joml.Quaterniond arg0);
    double lengthSquared();
    org.joml.Quaterniond slerp(org.joml.Quaterniondc arg0, double arg1, org.joml.Quaterniond arg2);
    org.joml.Quaterniond scale(double arg0, org.joml.Quaterniond arg1);
    org.joml.Quaterniond integrate(double arg0, double arg1, double arg2, double arg3, org.joml.Quaterniond arg4);
    org.joml.Quaterniond nlerp(org.joml.Quaterniondc arg0, double arg1, org.joml.Quaterniond arg2);
    org.joml.Quaterniond nlerpIterative(org.joml.Quaterniondc arg0, double arg1, double arg2, org.joml.Quaterniond arg3);
    org.joml.Quaterniond lookAlong(org.joml.Vector3dc arg0, org.joml.Vector3dc arg1, org.joml.Quaterniond arg2);
    org.joml.Quaterniond lookAlong(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, org.joml.Quaterniond arg6);
    org.joml.Quaterniond difference(org.joml.Quaterniondc arg0, org.joml.Quaterniond arg1);
    org.joml.Quaterniond rotateTo(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5, org.joml.Quaterniond arg6);
    org.joml.Quaterniond rotateTo(org.joml.Vector3dc arg0, org.joml.Vector3dc arg1, org.joml.Quaterniond arg2);
    org.joml.Quaterniond rotateX(double arg0, org.joml.Quaterniond arg1);
    org.joml.Quaterniond rotateY(double arg0, org.joml.Quaterniond arg1);
    org.joml.Quaterniond rotateZ(double arg0, org.joml.Quaterniond arg1);
    org.joml.Quaterniond rotateLocalX(double arg0, org.joml.Quaterniond arg1);
    org.joml.Quaterniond rotateLocalY(double arg0, org.joml.Quaterniond arg1);
    org.joml.Quaterniond rotateLocalZ(double arg0, org.joml.Quaterniond arg1);
    org.joml.Quaterniond rotateXYZ(double arg0, double arg1, double arg2, org.joml.Quaterniond arg3);
    org.joml.Quaterniond rotateZYX(double arg0, double arg1, double arg2, org.joml.Quaterniond arg3);
    org.joml.Quaterniond rotateYXZ(double arg0, double arg1, double arg2, org.joml.Quaterniond arg3);
    org.joml.Vector3d getEulerAnglesXYZ(org.joml.Vector3d arg0);
    org.joml.Vector3d getEulerAnglesZYX(org.joml.Vector3d arg0);
    org.joml.Vector3d getEulerAnglesZXY(org.joml.Vector3d arg0);
    org.joml.Vector3d getEulerAnglesYXZ(org.joml.Vector3d arg0);
    org.joml.Quaterniond rotateAxis(double arg0, double arg1, double arg2, double arg3, org.joml.Quaterniond arg4);
    org.joml.Quaterniond rotateAxis(double arg0, org.joml.Vector3dc arg1, org.joml.Quaterniond arg2);
    org.joml.Vector3d positiveX(org.joml.Vector3d arg0);
    org.joml.Vector3d normalizedPositiveX(org.joml.Vector3d arg0);
    org.joml.Vector3d positiveY(org.joml.Vector3d arg0);
    org.joml.Vector3d normalizedPositiveY(org.joml.Vector3d arg0);
    org.joml.Vector3d positiveZ(org.joml.Vector3d arg0);
    org.joml.Vector3d normalizedPositiveZ(org.joml.Vector3d arg0);
    org.joml.Quaterniond conjugateBy(org.joml.Quaterniondc arg0, org.joml.Quaterniond arg1);
    boolean isFinite();
    boolean equals(org.joml.Quaterniondc arg0, double arg1);
    boolean equals(double arg0, double arg1, double arg2, double arg3);
}
