package org.joml;

/** Auto-generated stub from paper-api-26.1.2.build.20-alpha.jar. See PLAN-FULL-STUBS.md. */
@SuppressWarnings({"unchecked", "rawtypes", "unused"})
public interface Quaternionfc {
    float x();
    float y();
    float z();
    float w();
    org.joml.Quaternionf normalize(org.joml.Quaternionf arg0);
    org.joml.Quaternionf add(float arg0, float arg1, float arg2, float arg3, org.joml.Quaternionf arg4);
    org.joml.Quaternionf add(org.joml.Quaternionfc arg0, org.joml.Quaternionf arg1);
    org.joml.Quaternionf sub(float arg0, float arg1, float arg2, float arg3, org.joml.Quaternionf arg4);
    org.joml.Quaternionf sub(org.joml.Quaternionfc arg0, org.joml.Quaternionf arg1);
    float angle();
    org.joml.Matrix3f get(org.joml.Matrix3f arg0);
    org.joml.Matrix3d get(org.joml.Matrix3d arg0);
    org.joml.Matrix4f get(org.joml.Matrix4f arg0);
    org.joml.Matrix4d get(org.joml.Matrix4d arg0);
    org.joml.Matrix4x3f get(org.joml.Matrix4x3f arg0);
    org.joml.Matrix4x3d get(org.joml.Matrix4x3d arg0);
    org.joml.AxisAngle4f get(org.joml.AxisAngle4f arg0);
    org.joml.AxisAngle4d get(org.joml.AxisAngle4d arg0);
    org.joml.Quaterniond get(org.joml.Quaterniond arg0);
    org.joml.Quaternionf get(org.joml.Quaternionf arg0);
    java.nio.ByteBuffer getAsMatrix3f(java.nio.ByteBuffer arg0);
    java.nio.FloatBuffer getAsMatrix3f(java.nio.FloatBuffer arg0);
    java.nio.ByteBuffer getAsMatrix4f(java.nio.ByteBuffer arg0);
    java.nio.FloatBuffer getAsMatrix4f(java.nio.FloatBuffer arg0);
    java.nio.ByteBuffer getAsMatrix4x3f(java.nio.ByteBuffer arg0);
    java.nio.FloatBuffer getAsMatrix4x3f(java.nio.FloatBuffer arg0);
    org.joml.Quaternionf mul(org.joml.Quaternionfc arg0, org.joml.Quaternionf arg1);
    org.joml.Quaternionf mul(float arg0, float arg1, float arg2, float arg3, org.joml.Quaternionf arg4);
    org.joml.Quaternionf mul(float arg0, org.joml.Quaternionf arg1);
    org.joml.Quaternionf premul(org.joml.Quaternionfc arg0, org.joml.Quaternionf arg1);
    org.joml.Quaternionf premul(float arg0, float arg1, float arg2, float arg3, org.joml.Quaternionf arg4);
    org.joml.Vector3f transform(org.joml.Vector3f arg0);
    org.joml.Vector3f transformInverse(org.joml.Vector3f arg0);
    org.joml.Vector3f transformUnit(org.joml.Vector3f arg0);
    org.joml.Vector3f transformPositiveX(org.joml.Vector3f arg0);
    org.joml.Vector4f transformPositiveX(org.joml.Vector4f arg0);
    org.joml.Vector3f transformUnitPositiveX(org.joml.Vector3f arg0);
    org.joml.Vector4f transformUnitPositiveX(org.joml.Vector4f arg0);
    org.joml.Vector3f transformPositiveY(org.joml.Vector3f arg0);
    org.joml.Vector4f transformPositiveY(org.joml.Vector4f arg0);
    org.joml.Vector3f transformUnitPositiveY(org.joml.Vector3f arg0);
    org.joml.Vector4f transformUnitPositiveY(org.joml.Vector4f arg0);
    org.joml.Vector3f transformPositiveZ(org.joml.Vector3f arg0);
    org.joml.Vector4f transformPositiveZ(org.joml.Vector4f arg0);
    org.joml.Vector3f transformUnitPositiveZ(org.joml.Vector3f arg0);
    org.joml.Vector4f transformUnitPositiveZ(org.joml.Vector4f arg0);
    org.joml.Vector4f transform(org.joml.Vector4f arg0);
    org.joml.Vector4f transformInverse(org.joml.Vector4f arg0);
    org.joml.Vector3f transform(org.joml.Vector3fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f transformInverse(org.joml.Vector3fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f transform(float arg0, float arg1, float arg2, org.joml.Vector3f arg3);
    org.joml.Vector3d transform(float arg0, float arg1, float arg2, org.joml.Vector3d arg3);
    org.joml.Vector3f transformInverse(float arg0, float arg1, float arg2, org.joml.Vector3f arg3);
    org.joml.Vector3d transformInverse(float arg0, float arg1, float arg2, org.joml.Vector3d arg3);
    org.joml.Vector3f transformInverseUnit(org.joml.Vector3f arg0);
    org.joml.Vector3f transformUnit(org.joml.Vector3fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f transformInverseUnit(org.joml.Vector3fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f transformUnit(float arg0, float arg1, float arg2, org.joml.Vector3f arg3);
    org.joml.Vector3d transformUnit(float arg0, float arg1, float arg2, org.joml.Vector3d arg3);
    org.joml.Vector3f transformInverseUnit(float arg0, float arg1, float arg2, org.joml.Vector3f arg3);
    org.joml.Vector3d transformInverseUnit(float arg0, float arg1, float arg2, org.joml.Vector3d arg3);
    org.joml.Vector4f transform(org.joml.Vector4fc arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f transformInverse(org.joml.Vector4fc arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f transform(float arg0, float arg1, float arg2, org.joml.Vector4f arg3);
    org.joml.Vector4f transformInverse(float arg0, float arg1, float arg2, org.joml.Vector4f arg3);
    org.joml.Vector4f transformUnit(org.joml.Vector4fc arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f transformUnit(org.joml.Vector4f arg0);
    org.joml.Vector4f transformInverseUnit(org.joml.Vector4f arg0);
    org.joml.Vector4f transformInverseUnit(org.joml.Vector4fc arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f transformUnit(float arg0, float arg1, float arg2, org.joml.Vector4f arg3);
    org.joml.Vector4f transformInverseUnit(float arg0, float arg1, float arg2, org.joml.Vector4f arg3);
    org.joml.Vector3d transform(org.joml.Vector3d arg0);
    org.joml.Vector3d transformInverse(org.joml.Vector3d arg0);
    org.joml.Vector3d transformPositiveX(org.joml.Vector3d arg0);
    org.joml.Vector4d transformPositiveX(org.joml.Vector4d arg0);
    org.joml.Vector3d transformUnitPositiveX(org.joml.Vector3d arg0);
    org.joml.Vector4d transformUnitPositiveX(org.joml.Vector4d arg0);
    org.joml.Vector3d transformPositiveY(org.joml.Vector3d arg0);
    org.joml.Vector4d transformPositiveY(org.joml.Vector4d arg0);
    org.joml.Vector3d transformUnitPositiveY(org.joml.Vector3d arg0);
    org.joml.Vector4d transformUnitPositiveY(org.joml.Vector4d arg0);
    org.joml.Vector3d transformPositiveZ(org.joml.Vector3d arg0);
    org.joml.Vector4d transformPositiveZ(org.joml.Vector4d arg0);
    org.joml.Vector3d transformUnitPositiveZ(org.joml.Vector3d arg0);
    org.joml.Vector4d transformUnitPositiveZ(org.joml.Vector4d arg0);
    org.joml.Vector4d transform(org.joml.Vector4d arg0);
    org.joml.Vector4d transformInverse(org.joml.Vector4d arg0);
    org.joml.Vector3d transform(org.joml.Vector3dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d transformInverse(org.joml.Vector3dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d transform(double arg0, double arg1, double arg2, org.joml.Vector3d arg3);
    org.joml.Vector3d transformInverse(double arg0, double arg1, double arg2, org.joml.Vector3d arg3);
    org.joml.Vector4d transform(org.joml.Vector4dc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d transformInverse(org.joml.Vector4dc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d transform(double arg0, double arg1, double arg2, org.joml.Vector4d arg3);
    org.joml.Vector4d transformInverse(double arg0, double arg1, double arg2, org.joml.Vector4d arg3);
    org.joml.Vector4d transformUnit(org.joml.Vector4d arg0);
    org.joml.Vector4d transformInverseUnit(org.joml.Vector4d arg0);
    org.joml.Vector3d transformUnit(org.joml.Vector3dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d transformInverseUnit(org.joml.Vector3dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d transformUnit(double arg0, double arg1, double arg2, org.joml.Vector3d arg3);
    org.joml.Vector3d transformInverseUnit(double arg0, double arg1, double arg2, org.joml.Vector3d arg3);
    org.joml.Vector4d transformUnit(org.joml.Vector4dc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d transformInverseUnit(org.joml.Vector4dc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d transformUnit(double arg0, double arg1, double arg2, org.joml.Vector4d arg3);
    org.joml.Vector4d transformInverseUnit(double arg0, double arg1, double arg2, org.joml.Vector4d arg3);
    org.joml.Quaternionf invert(org.joml.Quaternionf arg0);
    org.joml.Quaternionf div(org.joml.Quaternionfc arg0, org.joml.Quaternionf arg1);
    org.joml.Quaternionf div(float arg0, org.joml.Quaternionf arg1);
    org.joml.Quaternionf conjugate(org.joml.Quaternionf arg0);
    org.joml.Quaternionf rotateXYZ(float arg0, float arg1, float arg2, org.joml.Quaternionf arg3);
    org.joml.Quaternionf rotateZYX(float arg0, float arg1, float arg2, org.joml.Quaternionf arg3);
    org.joml.Quaternionf rotateYXZ(float arg0, float arg1, float arg2, org.joml.Quaternionf arg3);
    org.joml.Vector3f getEulerAnglesXYZ(org.joml.Vector3f arg0);
    org.joml.Vector3f getEulerAnglesZYX(org.joml.Vector3f arg0);
    org.joml.Vector3f getEulerAnglesZXY(org.joml.Vector3f arg0);
    org.joml.Vector3f getEulerAnglesYXZ(org.joml.Vector3f arg0);
    float lengthSquared();
    org.joml.Quaternionf slerp(org.joml.Quaternionfc arg0, float arg1, org.joml.Quaternionf arg2);
    org.joml.Quaternionf scale(float arg0, org.joml.Quaternionf arg1);
    org.joml.Quaternionf integrate(float arg0, float arg1, float arg2, float arg3, org.joml.Quaternionf arg4);
    org.joml.Quaternionf nlerp(org.joml.Quaternionfc arg0, float arg1, org.joml.Quaternionf arg2);
    org.joml.Quaternionf nlerpIterative(org.joml.Quaternionfc arg0, float arg1, float arg2, org.joml.Quaternionf arg3);
    org.joml.Quaternionf lookAlong(org.joml.Vector3fc arg0, org.joml.Vector3fc arg1, org.joml.Quaternionf arg2);
    org.joml.Quaternionf lookAlong(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, org.joml.Quaternionf arg6);
    org.joml.Quaternionf rotateTo(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, org.joml.Quaternionf arg6);
    org.joml.Quaternionf rotateTo(org.joml.Vector3fc arg0, org.joml.Vector3fc arg1, org.joml.Quaternionf arg2);
    org.joml.Quaternionf rotateX(float arg0, org.joml.Quaternionf arg1);
    org.joml.Quaternionf rotateY(float arg0, org.joml.Quaternionf arg1);
    org.joml.Quaternionf rotateZ(float arg0, org.joml.Quaternionf arg1);
    org.joml.Quaternionf rotateLocalX(float arg0, org.joml.Quaternionf arg1);
    org.joml.Quaternionf rotateLocalY(float arg0, org.joml.Quaternionf arg1);
    org.joml.Quaternionf rotateLocalZ(float arg0, org.joml.Quaternionf arg1);
    org.joml.Quaternionf rotateAxis(float arg0, float arg1, float arg2, float arg3, org.joml.Quaternionf arg4);
    org.joml.Quaternionf rotateAxis(float arg0, org.joml.Vector3fc arg1, org.joml.Quaternionf arg2);
    org.joml.Quaternionf difference(org.joml.Quaternionfc arg0, org.joml.Quaternionf arg1);
    org.joml.Vector3f positiveX(org.joml.Vector3f arg0);
    org.joml.Vector3f normalizedPositiveX(org.joml.Vector3f arg0);
    org.joml.Vector3f positiveY(org.joml.Vector3f arg0);
    org.joml.Vector3f normalizedPositiveY(org.joml.Vector3f arg0);
    org.joml.Vector3f positiveZ(org.joml.Vector3f arg0);
    org.joml.Vector3f normalizedPositiveZ(org.joml.Vector3f arg0);
    org.joml.Quaternionf conjugateBy(org.joml.Quaternionfc arg0, org.joml.Quaternionf arg1);
    boolean isFinite();
    boolean equals(org.joml.Quaternionfc arg0, float arg1);
    boolean equals(float arg0, float arg1, float arg2, float arg3);
}
