package org.joml;

/** Auto-generated stub from paper-api-26.1.2.build.20-alpha.jar. See PLAN-FULL-STUBS.md. */
@SuppressWarnings({"unchecked", "rawtypes", "unused"})
public interface Vector4dc {
    double x();
    double y();
    double z();
    double w();
    java.nio.ByteBuffer get(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer get(int arg0, java.nio.ByteBuffer arg1);
    java.nio.DoubleBuffer get(java.nio.DoubleBuffer arg0);
    java.nio.DoubleBuffer get(int arg0, java.nio.DoubleBuffer arg1);
    java.nio.FloatBuffer get(java.nio.FloatBuffer arg0);
    java.nio.FloatBuffer get(int arg0, java.nio.FloatBuffer arg1);
    java.nio.ByteBuffer getf(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer getf(int arg0, java.nio.ByteBuffer arg1);
    org.joml.Vector4dc getToAddress(long arg0);
    org.joml.Vector4d sub(org.joml.Vector4dc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d sub(org.joml.Vector4fc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d sub(double arg0, double arg1, double arg2, double arg3, org.joml.Vector4d arg4);
    org.joml.Vector4d add(org.joml.Vector4dc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d add(org.joml.Vector4fc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d add(double arg0, double arg1, double arg2, double arg3, org.joml.Vector4d arg4);
    org.joml.Vector4d fma(org.joml.Vector4dc arg0, org.joml.Vector4dc arg1, org.joml.Vector4d arg2);
    org.joml.Vector4d fma(double arg0, org.joml.Vector4dc arg1, org.joml.Vector4d arg2);
    org.joml.Vector4d mul(org.joml.Vector4dc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d mul(org.joml.Vector4fc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d div(org.joml.Vector4dc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d mul(org.joml.Matrix4dc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d mul(org.joml.Matrix4x3dc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d mulGeneric(org.joml.Matrix4x3dc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d mulTranslation(org.joml.Matrix4x3dc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d mul(org.joml.Matrix4x3fc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d mulTranslation(org.joml.Matrix4x3fc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d mulGeneric(org.joml.Matrix4x3fc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d mul(org.joml.Matrix4fc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d mulGeneric(org.joml.Matrix4dc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d mulGeneric(org.joml.Matrix4fc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d mulTranspose(org.joml.Matrix4dc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d mulTranslation(org.joml.Matrix4dc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d mulTranslation(org.joml.Matrix4fc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d mulAffine(org.joml.Matrix4dc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d mulAffine(org.joml.Matrix4fc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d mulAffineTranspose(org.joml.Matrix4dc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d mulGenericTranspose(org.joml.Matrix4dc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d mulProject(org.joml.Matrix4dc arg0, org.joml.Vector4d arg1);
    org.joml.Vector3d mulProject(org.joml.Matrix4dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mulProjectGeneric(org.joml.Matrix4dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector4d mulProjectGeneric(org.joml.Matrix4dc arg0, org.joml.Vector4d arg1);
    org.joml.Vector3d mulProjectTranslation(org.joml.Matrix4dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector4d mulProjectTranslation(org.joml.Matrix4dc arg0, org.joml.Vector4d arg1);
    org.joml.Vector3d mulProjectAffine(org.joml.Matrix4dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector4d mulProjectAffine(org.joml.Matrix4dc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d mulAdd(org.joml.Vector4dc arg0, org.joml.Vector4dc arg1, org.joml.Vector4d arg2);
    org.joml.Vector4d mulAdd(double arg0, org.joml.Vector4dc arg1, org.joml.Vector4d arg2);
    org.joml.Vector4d mul(double arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d div(double arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d rotate(org.joml.Quaterniondc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d rotateAxis(double arg0, double arg1, double arg2, double arg3, org.joml.Vector4d arg4);
    org.joml.Vector4d rotateX(double arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d rotateY(double arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d rotateZ(double arg0, org.joml.Vector4d arg1);
    double lengthSquared();
    double length();
    org.joml.Vector4d normalize(org.joml.Vector4d arg0);
    org.joml.Vector4d normalize(double arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d normalize3(org.joml.Vector4d arg0);
    double distance(org.joml.Vector4dc arg0);
    double distance(double arg0, double arg1, double arg2, double arg3);
    double distanceSquared(org.joml.Vector4dc arg0);
    double distanceSquared(double arg0, double arg1, double arg2, double arg3);
    double dot(org.joml.Vector4dc arg0);
    double dot(double arg0, double arg1, double arg2, double arg3);
    double angleCos(org.joml.Vector4dc arg0);
    double angle(org.joml.Vector4dc arg0);
    org.joml.Vector4d negate(org.joml.Vector4d arg0);
    org.joml.Vector4d min(org.joml.Vector4dc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d max(org.joml.Vector4dc arg0, org.joml.Vector4d arg1);
    org.joml.Vector4d smoothStep(org.joml.Vector4dc arg0, double arg1, org.joml.Vector4d arg2);
    org.joml.Vector4d hermite(org.joml.Vector4dc arg0, org.joml.Vector4dc arg1, org.joml.Vector4dc arg2, double arg3, org.joml.Vector4d arg4);
    org.joml.Vector4d lerp(org.joml.Vector4dc arg0, double arg1, org.joml.Vector4d arg2);
    double get(int arg0) throws java.lang.IllegalArgumentException;
    org.joml.Vector4i get(int arg0, org.joml.Vector4i arg1);
    org.joml.Vector4f get(org.joml.Vector4f arg0);
    org.joml.Vector4d get(org.joml.Vector4d arg0);
    int maxComponent();
    int minComponent();
    org.joml.Vector4d floor(org.joml.Vector4d arg0);
    org.joml.Vector4d ceil(org.joml.Vector4d arg0);
    org.joml.Vector4d round(org.joml.Vector4d arg0);
    boolean isFinite();
    org.joml.Vector4d absolute(org.joml.Vector4d arg0);
    boolean equals(org.joml.Vector4dc arg0, double arg1);
    boolean equals(double arg0, double arg1, double arg2, double arg3);
}
