package org.joml;

/** Auto-generated stub from paper-api-26.1.2.build.20-alpha.jar. See PLAN-FULL-STUBS.md. */
@SuppressWarnings({"unchecked", "rawtypes", "unused"})
public interface Vector4fc {
    float x();
    float y();
    float z();
    float w();
    java.nio.FloatBuffer get(java.nio.FloatBuffer arg0);
    java.nio.FloatBuffer get(int arg0, java.nio.FloatBuffer arg1);
    java.nio.ByteBuffer get(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer get(int arg0, java.nio.ByteBuffer arg1);
    org.joml.Vector4fc getToAddress(long arg0);
    org.joml.Vector4f sub(org.joml.Vector4fc arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f sub(float arg0, float arg1, float arg2, float arg3, org.joml.Vector4f arg4);
    org.joml.Vector4f add(org.joml.Vector4fc arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f add(float arg0, float arg1, float arg2, float arg3, org.joml.Vector4f arg4);
    org.joml.Vector4f fma(org.joml.Vector4fc arg0, org.joml.Vector4fc arg1, org.joml.Vector4f arg2);
    org.joml.Vector4f fma(float arg0, org.joml.Vector4fc arg1, org.joml.Vector4f arg2);
    org.joml.Vector4f mulAdd(org.joml.Vector4fc arg0, org.joml.Vector4fc arg1, org.joml.Vector4f arg2);
    org.joml.Vector4f mulAdd(float arg0, org.joml.Vector4fc arg1, org.joml.Vector4f arg2);
    org.joml.Vector4f mul(org.joml.Vector4fc arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f div(org.joml.Vector4fc arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f mul(org.joml.Matrix4fc arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f mulGeneric(org.joml.Matrix4fc arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f mulTranspose(org.joml.Matrix4fc arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f mulTranslation(org.joml.Matrix4fc arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f mulAffine(org.joml.Matrix4fc arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f mulAffineTranspose(org.joml.Matrix4fc arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f mulGenericTranspose(org.joml.Matrix4fc arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f mul(org.joml.Matrix4x3fc arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f mulTranslation(org.joml.Matrix4x3fc arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f mulGeneric(org.joml.Matrix4x3fc arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f mulProject(org.joml.Matrix4fc arg0, org.joml.Vector4f arg1);
    org.joml.Vector3f mulProject(org.joml.Matrix4fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f mulProjectGeneric(org.joml.Matrix4fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector4f mulProjectGeneric(org.joml.Matrix4fc arg0, org.joml.Vector4f arg1);
    org.joml.Vector3f mulProjectTranslation(org.joml.Matrix4fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector4f mulProjectTranslation(org.joml.Matrix4fc arg0, org.joml.Vector4f arg1);
    org.joml.Vector3f mulProjectAffine(org.joml.Matrix4fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector4f mulProjectAffine(org.joml.Matrix4fc arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f mul(float arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f mul(float arg0, float arg1, float arg2, float arg3, org.joml.Vector4f arg4);
    org.joml.Vector4f div(float arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f div(float arg0, float arg1, float arg2, float arg3, org.joml.Vector4f arg4);
    org.joml.Vector4f rotate(org.joml.Quaternionfc arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f rotateAxis(float arg0, float arg1, float arg2, float arg3, org.joml.Vector4f arg4);
    org.joml.Vector4f rotateX(float arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f rotateY(float arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f rotateZ(float arg0, org.joml.Vector4f arg1);
    float lengthSquared();
    float length();
    org.joml.Vector4f normalize(org.joml.Vector4f arg0);
    org.joml.Vector4f normalize(float arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f normalize3(org.joml.Vector4f arg0);
    float distance(org.joml.Vector4fc arg0);
    float distance(float arg0, float arg1, float arg2, float arg3);
    float distanceSquared(org.joml.Vector4fc arg0);
    float distanceSquared(float arg0, float arg1, float arg2, float arg3);
    float dot(org.joml.Vector4fc arg0);
    float dot(float arg0, float arg1, float arg2, float arg3);
    float angleCos(org.joml.Vector4fc arg0);
    float angle(org.joml.Vector4fc arg0);
    org.joml.Vector4f negate(org.joml.Vector4f arg0);
    org.joml.Vector4f min(org.joml.Vector4fc arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f max(org.joml.Vector4fc arg0, org.joml.Vector4f arg1);
    org.joml.Vector4f lerp(org.joml.Vector4fc arg0, float arg1, org.joml.Vector4f arg2);
    org.joml.Vector4f smoothStep(org.joml.Vector4fc arg0, float arg1, org.joml.Vector4f arg2);
    org.joml.Vector4f hermite(org.joml.Vector4fc arg0, org.joml.Vector4fc arg1, org.joml.Vector4fc arg2, float arg3, org.joml.Vector4f arg4);
    float get(int arg0) throws java.lang.IllegalArgumentException;
    org.joml.Vector4i get(int arg0, org.joml.Vector4i arg1);
    org.joml.Vector4f get(org.joml.Vector4f arg0);
    org.joml.Vector4d get(org.joml.Vector4d arg0);
    int maxComponent();
    int minComponent();
    org.joml.Vector4f floor(org.joml.Vector4f arg0);
    org.joml.Vector4f ceil(org.joml.Vector4f arg0);
    org.joml.Vector4f round(org.joml.Vector4f arg0);
    boolean isFinite();
    org.joml.Vector4f absolute(org.joml.Vector4f arg0);
    boolean equals(org.joml.Vector4fc arg0, float arg1);
    boolean equals(float arg0, float arg1, float arg2, float arg3);
}
