package org.joml;

/** Auto-generated stub from paper-api-26.1.2.build.20-alpha.jar. See PLAN-FULL-STUBS.md. */
@SuppressWarnings({"unchecked", "rawtypes", "unused"})
public interface Vector3dc {
    double x();
    double y();
    double z();
    java.nio.ByteBuffer get(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer get(int arg0, java.nio.ByteBuffer arg1);
    java.nio.DoubleBuffer get(java.nio.DoubleBuffer arg0);
    java.nio.DoubleBuffer get(int arg0, java.nio.DoubleBuffer arg1);
    java.nio.FloatBuffer get(java.nio.FloatBuffer arg0);
    java.nio.FloatBuffer get(int arg0, java.nio.FloatBuffer arg1);
    java.nio.ByteBuffer getf(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer getf(int arg0, java.nio.ByteBuffer arg1);
    org.joml.Vector3dc getToAddress(long arg0);
    org.joml.Vector3d sub(org.joml.Vector3dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d sub(org.joml.Vector3fc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d sub(double arg0, double arg1, double arg2, org.joml.Vector3d arg3);
    org.joml.Vector3d add(org.joml.Vector3dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d add(org.joml.Vector3fc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d add(double arg0, double arg1, double arg2, org.joml.Vector3d arg3);
    org.joml.Vector3d fma(org.joml.Vector3dc arg0, org.joml.Vector3dc arg1, org.joml.Vector3d arg2);
    org.joml.Vector3d fma(double arg0, org.joml.Vector3dc arg1, org.joml.Vector3d arg2);
    org.joml.Vector3d fma(org.joml.Vector3dc arg0, org.joml.Vector3fc arg1, org.joml.Vector3d arg2);
    org.joml.Vector3d fma(org.joml.Vector3fc arg0, org.joml.Vector3fc arg1, org.joml.Vector3d arg2);
    org.joml.Vector3d fma(double arg0, org.joml.Vector3fc arg1, org.joml.Vector3d arg2);
    org.joml.Vector3d mulAdd(org.joml.Vector3dc arg0, org.joml.Vector3dc arg1, org.joml.Vector3d arg2);
    org.joml.Vector3d mulAdd(double arg0, org.joml.Vector3dc arg1, org.joml.Vector3d arg2);
    org.joml.Vector3d mulAdd(org.joml.Vector3fc arg0, org.joml.Vector3dc arg1, org.joml.Vector3d arg2);
    org.joml.Vector3d mul(org.joml.Vector3fc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mul(org.joml.Vector3dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d div(org.joml.Vector3fc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d div(org.joml.Vector3dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mulProject(org.joml.Matrix4dc arg0, double arg1, org.joml.Vector3d arg2);
    org.joml.Vector3d mulProject(org.joml.Matrix4dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mulProject(org.joml.Matrix4fc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mulProjectTranslation(org.joml.Matrix4fc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mulProjectTranslation(org.joml.Matrix4dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mulProjectAffine(org.joml.Matrix4fc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mulProjectGeneric(org.joml.Matrix4fc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mulProjectGeneric(org.joml.Matrix4dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mulProjectAffine(org.joml.Matrix4dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mul(org.joml.Matrix3dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3f mul(org.joml.Matrix3dc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3d mul(org.joml.Matrix3fc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mul(org.joml.Matrix3x2dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mul(org.joml.Matrix3x2fc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mulTranspose(org.joml.Matrix3dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mulTranspose(org.joml.Matrix3fc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mulPosition(org.joml.Matrix4dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mulPositionGeneric(org.joml.Matrix4dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mulPositionTranslation(org.joml.Matrix4dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mulPosition(org.joml.Matrix4fc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mulPositionGeneric(org.joml.Matrix4fc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mulPositionTranslation(org.joml.Matrix4fc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mulPosition(org.joml.Matrix4x3dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mulPositionGeneric(org.joml.Matrix4x3dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mulPositionTranslation(org.joml.Matrix4x3dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mulPosition(org.joml.Matrix4x3fc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mulPositionGeneric(org.joml.Matrix4x3fc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mulPositionTranslation(org.joml.Matrix4x3fc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mulTransposePosition(org.joml.Matrix4dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mulTransposePosition(org.joml.Matrix4fc arg0, org.joml.Vector3d arg1);
    double mulPositionW(org.joml.Matrix4fc arg0, org.joml.Vector3d arg1);
    double mulPositionW(org.joml.Matrix4dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mulDirection(org.joml.Matrix4dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mulDirection(org.joml.Matrix4fc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mulDirection(org.joml.Matrix4x3dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mulDirection(org.joml.Matrix4x3fc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mulTransposeDirection(org.joml.Matrix4dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mulTransposeDirection(org.joml.Matrix4fc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mul(double arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d mul(double arg0, double arg1, double arg2, org.joml.Vector3d arg3);
    org.joml.Vector3d rotate(org.joml.Quaterniondc arg0, org.joml.Vector3d arg1);
    org.joml.Quaterniond rotationTo(org.joml.Vector3dc arg0, org.joml.Quaterniond arg1);
    org.joml.Quaterniond rotationTo(double arg0, double arg1, double arg2, org.joml.Quaterniond arg3);
    org.joml.Vector3d rotateAxis(double arg0, double arg1, double arg2, double arg3, org.joml.Vector3d arg4);
    org.joml.Vector3d rotateX(double arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d rotateY(double arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d rotateZ(double arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d div(double arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d div(double arg0, double arg1, double arg2, org.joml.Vector3d arg3);
    double lengthSquared();
    double length();
    org.joml.Vector3d normalize(org.joml.Vector3d arg0);
    org.joml.Vector3d normalize(double arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d cross(org.joml.Vector3dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d cross(double arg0, double arg1, double arg2, org.joml.Vector3d arg3);
    double distance(org.joml.Vector3dc arg0);
    double distance(double arg0, double arg1, double arg2);
    double distanceSquared(org.joml.Vector3dc arg0);
    double distanceSquared(double arg0, double arg1, double arg2);
    double dot(org.joml.Vector3dc arg0);
    double dot(double arg0, double arg1, double arg2);
    double angleCos(org.joml.Vector3dc arg0);
    double angle(org.joml.Vector3dc arg0);
    double angleSigned(org.joml.Vector3dc arg0, org.joml.Vector3dc arg1);
    double angleSigned(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5);
    org.joml.Vector3d min(org.joml.Vector3dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d max(org.joml.Vector3dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d negate(org.joml.Vector3d arg0);
    org.joml.Vector3d absolute(org.joml.Vector3d arg0);
    org.joml.Vector3d reflect(org.joml.Vector3dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d reflect(double arg0, double arg1, double arg2, org.joml.Vector3d arg3);
    org.joml.Vector3d half(org.joml.Vector3dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d half(double arg0, double arg1, double arg2, org.joml.Vector3d arg3);
    org.joml.Vector3d smoothStep(org.joml.Vector3dc arg0, double arg1, org.joml.Vector3d arg2);
    org.joml.Vector3d hermite(org.joml.Vector3dc arg0, org.joml.Vector3dc arg1, org.joml.Vector3dc arg2, double arg3, org.joml.Vector3d arg4);
    org.joml.Vector3d lerp(org.joml.Vector3dc arg0, double arg1, org.joml.Vector3d arg2);
    double get(int arg0) throws java.lang.IllegalArgumentException;
    org.joml.Vector3i get(int arg0, org.joml.Vector3i arg1);
    org.joml.Vector3f get(org.joml.Vector3f arg0);
    org.joml.Vector3d get(org.joml.Vector3d arg0);
    int maxComponent();
    int minComponent();
    org.joml.Vector3d orthogonalize(org.joml.Vector3dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d orthogonalizeUnit(org.joml.Vector3dc arg0, org.joml.Vector3d arg1);
    org.joml.Vector3d floor(org.joml.Vector3d arg0);
    org.joml.Vector3d ceil(org.joml.Vector3d arg0);
    org.joml.Vector3d round(org.joml.Vector3d arg0);
    boolean isFinite();
    boolean equals(org.joml.Vector3dc arg0, double arg1);
    boolean equals(double arg0, double arg1, double arg2);
}
