package org.joml;

/** Auto-generated stub from paper-api-26.1.2.build.20-alpha.jar. See PLAN-FULL-STUBS.md. */
@SuppressWarnings({"unchecked", "rawtypes", "unused"})
public interface Vector3fc {
    float x();
    float y();
    float z();
    java.nio.FloatBuffer get(java.nio.FloatBuffer arg0);
    java.nio.FloatBuffer get(int arg0, java.nio.FloatBuffer arg1);
    java.nio.ByteBuffer get(java.nio.ByteBuffer arg0);
    java.nio.ByteBuffer get(int arg0, java.nio.ByteBuffer arg1);
    org.joml.Vector3fc getToAddress(long arg0);
    org.joml.Vector3f sub(org.joml.Vector3fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f sub(float arg0, float arg1, float arg2, org.joml.Vector3f arg3);
    org.joml.Vector3f add(org.joml.Vector3fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f add(float arg0, float arg1, float arg2, org.joml.Vector3f arg3);
    org.joml.Vector3f fma(org.joml.Vector3fc arg0, org.joml.Vector3fc arg1, org.joml.Vector3f arg2);
    org.joml.Vector3f fma(float arg0, org.joml.Vector3fc arg1, org.joml.Vector3f arg2);
    org.joml.Vector3f mulAdd(org.joml.Vector3fc arg0, org.joml.Vector3fc arg1, org.joml.Vector3f arg2);
    org.joml.Vector3f mulAdd(float arg0, org.joml.Vector3fc arg1, org.joml.Vector3f arg2);
    org.joml.Vector3f mul(org.joml.Vector3fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f div(org.joml.Vector3fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f mulProject(org.joml.Matrix4fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f mulProject(org.joml.Matrix4fc arg0, float arg1, org.joml.Vector3f arg2);
    org.joml.Vector3f mulProjectTranslation(org.joml.Matrix4fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f mulProjectTranslation(org.joml.Matrix4dc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f mulProjectAffine(org.joml.Matrix4fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f mulProjectAffine(org.joml.Matrix4dc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f mulProjectGeneric(org.joml.Matrix4fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f mulProjectGeneric(org.joml.Matrix4dc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f mul(org.joml.Matrix3fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f mul(org.joml.Matrix3dc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f mul(org.joml.Matrix3x2fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f mul(org.joml.Matrix3x2dc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f mulTranspose(org.joml.Matrix3fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f mulPosition(org.joml.Matrix4fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f mulPosition(org.joml.Matrix4dc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f mulPosition(org.joml.Matrix4x3fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f mulPosition(org.joml.Matrix4x3dc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f mulPositionGeneric(org.joml.Matrix4fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f mulPositionGeneric(org.joml.Matrix4dc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f mulPositionTranslation(org.joml.Matrix4fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f mulPositionTranslation(org.joml.Matrix4dc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f mulPositionTranslation(org.joml.Matrix4x3fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f mulPositionTranslation(org.joml.Matrix4x3dc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f mulTransposePosition(org.joml.Matrix4fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f mulTransposePosition(org.joml.Matrix4dc arg0, org.joml.Vector3f arg1);
    float mulPositionW(org.joml.Matrix4fc arg0, org.joml.Vector3f arg1);
    float mulPositionW(org.joml.Matrix4dc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f mulDirection(org.joml.Matrix4dc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f mulDirection(org.joml.Matrix4fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f mulDirection(org.joml.Matrix4x3fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f mulDirection(org.joml.Matrix4x3dc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f mulTransposeDirection(org.joml.Matrix4fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f mul(float arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f mul(float arg0, float arg1, float arg2, org.joml.Vector3f arg3);
    org.joml.Vector3f div(float arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f div(float arg0, float arg1, float arg2, org.joml.Vector3f arg3);
    org.joml.Vector3f rotate(org.joml.Quaternionfc arg0, org.joml.Vector3f arg1);
    org.joml.Quaternionf rotationTo(org.joml.Vector3fc arg0, org.joml.Quaternionf arg1);
    org.joml.Quaternionf rotationTo(float arg0, float arg1, float arg2, org.joml.Quaternionf arg3);
    org.joml.Vector3f rotateAxis(float arg0, float arg1, float arg2, float arg3, org.joml.Vector3f arg4);
    org.joml.Vector3f rotateX(float arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f rotateY(float arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f rotateZ(float arg0, org.joml.Vector3f arg1);
    float lengthSquared();
    float length();
    org.joml.Vector3f normalize(org.joml.Vector3f arg0);
    org.joml.Vector3f normalize(float arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f cross(org.joml.Vector3fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f cross(float arg0, float arg1, float arg2, org.joml.Vector3f arg3);
    float distance(org.joml.Vector3fc arg0);
    float distance(float arg0, float arg1, float arg2);
    float distanceSquared(org.joml.Vector3fc arg0);
    float distanceSquared(float arg0, float arg1, float arg2);
    float dot(org.joml.Vector3fc arg0);
    float dot(float arg0, float arg1, float arg2);
    float angleCos(org.joml.Vector3fc arg0);
    float angle(org.joml.Vector3fc arg0);
    float angleSigned(org.joml.Vector3fc arg0, org.joml.Vector3fc arg1);
    float angleSigned(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5);
    org.joml.Vector3f min(org.joml.Vector3fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f max(org.joml.Vector3fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f negate(org.joml.Vector3f arg0);
    org.joml.Vector3f absolute(org.joml.Vector3f arg0);
    org.joml.Vector3f reflect(org.joml.Vector3fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f reflect(float arg0, float arg1, float arg2, org.joml.Vector3f arg3);
    org.joml.Vector3f half(org.joml.Vector3fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f half(float arg0, float arg1, float arg2, org.joml.Vector3f arg3);
    org.joml.Vector3f smoothStep(org.joml.Vector3fc arg0, float arg1, org.joml.Vector3f arg2);
    org.joml.Vector3f hermite(org.joml.Vector3fc arg0, org.joml.Vector3fc arg1, org.joml.Vector3fc arg2, float arg3, org.joml.Vector3f arg4);
    org.joml.Vector3f lerp(org.joml.Vector3fc arg0, float arg1, org.joml.Vector3f arg2);
    float get(int arg0) throws java.lang.IllegalArgumentException;
    org.joml.Vector3i get(int arg0, org.joml.Vector3i arg1);
    org.joml.Vector3f get(org.joml.Vector3f arg0);
    org.joml.Vector3d get(org.joml.Vector3d arg0);
    int maxComponent();
    int minComponent();
    org.joml.Vector3f orthogonalize(org.joml.Vector3fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f orthogonalizeUnit(org.joml.Vector3fc arg0, org.joml.Vector3f arg1);
    org.joml.Vector3f floor(org.joml.Vector3f arg0);
    org.joml.Vector3f ceil(org.joml.Vector3f arg0);
    org.joml.Vector3f round(org.joml.Vector3f arg0);
    boolean isFinite();
    boolean equals(org.joml.Vector3fc arg0, float arg1);
    boolean equals(float arg0, float arg1, float arg2);
}
