package org.bukkit;

/** Auto-generated stub from paper-api-26.1.2.build.20-alpha.jar. See PLAN-FULL-STUBS.md. */
@SuppressWarnings({"unchecked", "rawtypes", "unused"})
public enum Effect {
    CLICK2, CLICK1, BOW_FIRE, DOOR_TOGGLE, IRON_DOOR_TOGGLE, TRAPDOOR_TOGGLE, IRON_TRAPDOOR_TOGGLE, FENCE_GATE_TOGGLE, DOOR_CLOSE, IRON_DOOR_CLOSE, TRAPDOOR_CLOSE, IRON_TRAPDOOR_CLOSE, FENCE_GATE_CLOSE, EXTINGUISH, RECORD_PLAY, GHAST_SHRIEK, GHAST_SHOOT, BLAZE_SHOOT, ZOMBIE_CHEW_WOODEN_DOOR, ZOMBIE_CHEW_IRON_DOOR, ZOMBIE_DESTROY_DOOR, SMOKE, STEP_SOUND, POTION_BREAK, INSTANT_POTION_BREAK, ENDER_SIGNAL, MOBSPAWNER_FLAMES, BREWING_STAND_BREW, CHORUS_FLOWER_GROW, CHORUS_FLOWER_DEATH, PORTAL_TRAVEL, ENDEREYE_LAUNCH, FIREWORK_SHOOT, VILLAGER_PLANT_GROW, DRAGON_BREATH, ANVIL_BREAK, ANVIL_USE, ANVIL_LAND, ENDERDRAGON_SHOOT, WITHER_BREAK_BLOCK, WITHER_SHOOT, ZOMBIE_INFECT, ZOMBIE_CONVERTED_VILLAGER, BAT_TAKEOFF, END_GATEWAY_SPAWN, ENDERDRAGON_GROWL, PHANTOM_BITE, ZOMBIE_CONVERTED_TO_DROWNED, HUSK_CONVERTED_TO_ZOMBIE, GRINDSTONE_USE, BOOK_PAGE_TURN, SMITHING_TABLE_USE, POINTED_DRIPSTONE_LAND, POINTED_DRIPSTONE_DRIP_LAVA_INTO_CAULDRON, POINTED_DRIPSTONE_DRIP_WATER_INTO_CAULDRON, SKELETON_CONVERTED_TO_STRAY, COMPOSTER_FILL_ATTEMPT, LAVA_INTERACT, REDSTONE_TORCH_BURNOUT, END_PORTAL_FRAME_FILL, DRIPPING_DRIPSTONE, BONE_MEAL_USE, ENDER_DRAGON_DESTROY_BLOCK, SPONGE_DRY, ELECTRIC_SPARK, COPPER_WAX_ON, COPPER_WAX_OFF, OXIDISED_COPPER_SCRAPE, WITHER_SPAWNED, ENDER_DRAGON_DEATH, END_PORTAL_CREATED_IN_OVERWORLD, SOUND_STOP_JUKEBOX_SONG, CRAFTER_CRAFT, CRAFTER_FAIL, SHOOT_WHITE_SMOKE, BEE_GROWTH, TURTLE_EGG_PLACEMENT, SMASH_ATTACK, PARTICLES_SCULK_CHARGE, PARTICLES_SCULK_SHRIEK, PARTICLES_AND_SOUND_BRUSH_BLOCK_COMPLETE, PARTICLES_EGG_CRACK, GUST_DUST, TRIAL_SPAWNER_SPAWN, TRIAL_SPAWNER_SPAWN_MOB_AT, TRIAL_SPAWNER_DETECT_PLAYER, TRIAL_SPAWNER_EJECT_ITEM, VAULT_ACTIVATE, VAULT_DEACTIVATE, VAULT_EJECT_ITEM, SPAWN_COBWEB, TRIAL_SPAWNER_DETECT_PLAYER_OMINOUS, TRIAL_SPAWNER_BECOME_OMINOUS, TRIAL_SPAWNER_SPAWN_ITEM, SOUND_WITH_CHARGE_SHOT;
    public int getId() {
        return 0;
    }
    public org.bukkit.Effect$Type getType() {
        return null;
    }
    public java.lang.Class getData() {
        return null;
    }
    public boolean isApplicable(java.lang.Object arg0) {
        com.github.martinambrus.rdforward.api.stub.StubCallLog.logOnce(null, "org.bukkit.Effect.isApplicable(Ljava/lang/Object;)Z");
        return false;
    }
    public static org.bukkit.Effect getById(int arg0) {
        return null;
    }
}
