package org.bukkit;

/** Auto-generated stub from paper-api-26.1.2.build.20-alpha.jar. See PLAN-FULL-STUBS.md. */
@SuppressWarnings({"unchecked", "rawtypes", "unused"})
public enum Statistic implements org.bukkit.Keyed {
    ANIMALS_BRED, AVIATE_ONE_CM, BELL_RING, BOAT_ONE_CM, ARMOR_CLEANED, BANNER_CLEANED, CLEAN_SHULKER_BOX, CLIMB_ONE_CM, CROUCH_ONE_CM, DAMAGE_ABSORBED, DAMAGE_BLOCKED_BY_SHIELD, DAMAGE_DEALT, DAMAGE_DEALT_ABSORBED, DAMAGE_DEALT_RESISTED, DAMAGE_RESISTED, DAMAGE_TAKEN, DEATHS, DROP_COUNT, CAKE_SLICES_EATEN, ITEM_ENCHANTED, FALL_ONE_CM, CAULDRON_FILLED, FISH_CAUGHT, FLY_ONE_CM, HAPPY_GHAST_ONE_CM, HORSE_ONE_CM, DISPENSER_INSPECTED, DROPPER_INSPECTED, HOPPER_INSPECTED, INTERACT_WITH_ANVIL, BEACON_INTERACTION, INTERACT_WITH_BLAST_FURNACE, BREWINGSTAND_INTERACTION, INTERACT_WITH_CAMPFIRE, INTERACT_WITH_CARTOGRAPHY_TABLE, CRAFTING_TABLE_INTERACTION, FURNACE_INTERACTION, INTERACT_WITH_GRINDSTONE, INTERACT_WITH_LECTERN, INTERACT_WITH_LOOM, INTERACT_WITH_SMITHING_TABLE, INTERACT_WITH_SMOKER, INTERACT_WITH_STONECUTTER, JUMP, LEAVE_GAME, MINECART_ONE_CM, MOB_KILLS, NAUTILUS_ONE_CM, OPEN_BARREL, CHEST_OPENED, ENDERCHEST_OPENED, SHULKER_BOX_OPENED, PIG_ONE_CM, NOTEBLOCK_PLAYED, RECORD_PLAYED, PLAY_ONE_MINUTE, PLAYER_KILLS, FLOWER_POTTED, RAID_TRIGGER, RAID_WIN, SLEEP_IN_BED, SNEAK_TIME, SPRINT_ONE_CM, STRIDER_ONE_CM, SWIM_ONE_CM, TALKED_TO_VILLAGER, TARGET_HIT, TIME_SINCE_DEATH, TIME_SINCE_REST, TOTAL_WORLD_TIME, TRADED_WITH_VILLAGER, TRAPPED_CHEST_TRIGGERED, NOTEBLOCK_TUNED, CAULDRON_USED, WALK_ON_WATER_ONE_CM, WALK_ONE_CM, WALK_UNDER_WATER_ONE_CM, BREAK_ITEM, CRAFT_ITEM, DROP, KILL_ENTITY, ENTITY_KILLED_BY, MINE_BLOCK, PICKUP, USE_ITEM;
    public org.bukkit.Statistic$Type getType() {
        return null;
    }
    public boolean isSubstatistic() {
        return false;
    }
    public boolean isBlock() {
        return false;
    }
    public org.bukkit.NamespacedKey getKey() {
        return null;
    }
}
